### ISSUE TITLE
feat:(lua-api) opening the GrugFar panel with fields pre-filled

### ISSUE THREAD

**Issue by IndianBoy42** [MagicDuck/grug-far.nvim#1]
eg: opening GrugFar with the word under the cursor as the search term

eg: opening GrugFar with the file filter set to the current filetype

eg: opening GrugFar with/without some ripgrep flags

**Comment by MagicDuck** [comment]
sounds reasonable, just a matter of passing in args here https://github.com/MagicDuck/grug-far.nvim/blob/main/lua/grug-far.lua#L46C12-L46C20 and setting the text on the input lines in the buffer here: https://github.com/MagicDuck/grug-far.nvim/blob/main/lua/grug-far/farBuffer.lua#L58

**Comment by MagicDuck** [comment]
similar ask on reddit:
```
A quick point of feedback---can you make it obvious how this can be applied to only the current buffer file? Perhaps something as simple as a 'checkbox' or similar device?
```

**Comment by MagicDuck** [comment]
I'll try to do this soon 😄

**Comment by MagicDuck** [comment]
added, see here:
https://github.com/MagicDuck/grug-far.nvim?tab=readme-ov-file#%EF%B8%8F--lua-api
