### ISSUE TITLE
Check version of `rg`

### ISSUE THREAD

**Issue by bradsherman** [MagicDuck/grug-far.nvim#10]
I'm still on a version of `rg` less than `14` and I think because of that I get an error like `error: Found argument '--hyperlink-format' which wasn't expected, or isn't valid in this context`. Can the `--hyperlink-format` arg only get added if there's a version of `rg` that supports it? 

Alternatively if I could turn default flags off I could get around this as well.

**Comment by MagicDuck** [comment]
hmm I only added that from an abundance of caution. I'll remove it for now. Let me know if the problem persists and I'll reopen the issue 😄

**Comment by webpolis** [comment]
Problem persists. Using rg 13.0.0 installed via git repository.

**Comment by MagicDuck** [comment]
hmm, this regression was caused due to me adding it back cause it caused problems for people with the higher version. See: https://github.com/LazyVim/LazyVim/pull/4099#issuecomment-2241174757

**Comment by dotfrag** [comment]
@bradsherman is there a good reason you don't want to upgrade rg?

@MagicDuck one possible solution would be to check rg version and conditionally set the new flags, but that's an extra process call to rg.

**Comment by MagicDuck** [comment]
@dotfrag yep, that's what I ended up doing!
@webpolis Should be fixed now. Can you confirm?
Note, ideally you should upgrade to the higher version of rg, but am assuming there is some situation blocking you, right?

**Comment by dotfrag** [comment]
There's one situation I can think of.. some distros have older versions.. i.e. Ubuntu 22.04 is still sitting on rg v13 and won't upgrade it. On 24.04 they have 14 I think.
