### ISSUE TITLE
Command to toggle grug-far (feature request)

### ISSUE THREAD

**Issue by LandonSchropp** [MagicDuck/grug-far.nvim#106]
Overall, I'm really enjoying grug-far. However, one of the small niceties I'm used to from nvim-spectre is the ability to toggle the find/replace open and closed. Spectre accomplishes this with a `toggle` function which can be bound like this:

``` lua
vim.keymap.set('n', '<leader>fr', '<cmd>lua require("spectre").toggle()<cr>', {
    desc = "Find and replace"
})
```

Would it be possible to add similar functionality to grug-far? Maybe `GrugFarOptions` could contain a `toggle` flag?

Thank you! 🙏

**Comment by MagicDuck** [comment]
see comment in https://github.com/MagicDuck/grug-far.nvim/issues/105

**Comment by MagicDuck** [comment]
this would be the more appropriate place to discuss things, but unfortunately already posted stuff in https://github.com/MagicDuck/grug-far.nvim/issues/105 so closing this one and will continue the discussion there.
