### ISSUE TITLE
Go back to normal mode on quit.

### ISSUE THREAD

**Issue by razak17** [MagicDuck/grug-far.nvim#11]
When I exit using <C-x>. I stay in insert mode.
It will be nice to go back to normal mode.

**Comment by MagicDuck** [comment]
hmm, so the way it currently works is that whatever mode you are in when you exit, that is the mode you keep. This is just nvim default behaviour, not something special the plugin does. 
Are you requesting for an option to always switch back to normal mode when triggering the Close action (<C-x> by default)?

**Comment by razak17** [comment]
Exactly. I think adding that option will be a better user experience.
I think most users will expect that behavior cause it appears everywhere in many plugins/usecases.

Eg. When exiting a telescope prompt, lsp rename prompt, and many others,
the user gets switched back to normal mode.

**Comment by MagicDuck** [comment]
I played around with it a little and I think you are correct in your thinking! I think it makes sense to go back to normal on quit all the time, as it's easier to then navigate somewhere.

**Comment by MagicDuck** [comment]
closed in https://github.com/MagicDuck/grug-far.nvim/pull/20
