### ISSUE TITLE
Error during Sync: table index is nil

### ISSUE THREAD

**Issue by carlosflorencio** [MagicDuck/grug-far.nvim#110]
I have this error when syncing individual lines `,l` and all the lines `,s`:

```
E5108: Error executing lua: ...re/nvim/lazy/grug-far.nvim/lua/grug-far/actions/sync.lua:154: table index is nil
stack traceback:
        ...re/nvim/lazy/grug-far.nvim/lua/grug-far/actions/sync.lua:154: in function 'callback'
        ...m/lazy/grug-far.nvim/lua/grug-far/render/resultsList.lua:188: in function 'forEachChangedLocation'
        ...re/nvim/lazy/grug-far.nvim/lua/grug-far/actions/sync.lua:148: in function 'getChangedFiles'
        ...re/nvim/lazy/grug-far.nvim/lua/grug-far/actions/sync.lua:214: in function 'sync'
        ...vim/lazy/grug-far.nvim/lua/grug-far/actions/syncLine.lua:13: in function 'syncLine'
        ...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:48: in function <...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:47>
```

It happens when filtering for a file with flags set:
<img width="1281" alt="image" src="https://github.com/user-attachments/assets/600ae74b-53e2-4b89-8b76-3739098968d2">

This is the config I'm using:
```lua
  {
    'MagicDuck/grug-far.nvim',
    lazy = true,
    config = function()
      require('grug-far').setup {
        windowCreationCommand = 'tabnew %',
      }

      vim.api.nvim_create_autocmd('FileType', {
        group = vim.api.nvim_create_augroup('grugfar', { clear = true }),
        pattern = { 'grug-far' },
        callback = function()
          vim.keymap.set('n', '<localleader>w', function()
            local state = unpack(require('grug-far').toggle_flags { '--fixed-strings' })
            vim.notify('grug-far: toggled --fixed-strings ' .. (state and 'ON' or 'OFF'))
          end, { buffer = true })
        end,
      })
    end,
    keys = {
      {
        '<leader>sr',
        function()
          require('grug-far').grug_far { prefills = {
            search = vim.fn.expand '<cword>',
            flags = vim.fn.expand '%',
          } }
        end,
        desc = 'Replace in files (Spectre)',
      },
    },
  },

```

**Comment by carlosflorencio** [comment]
The readme seems to be wrong:
<img width="940" alt="image" src="https://github.com/user-attachments/assets/856b815d-d56e-41a1-9b8e-0042145b4e44">

Using `filesFilter` instead of `flags` works:

```lua
:lua require('grug-far').grug_far({ prefills = { filesFilter = vim.fn.expand("%") } })
```

**Comment by MagicDuck** [comment]
@carlosflorencio this is actually a bug 😄 
The sync code relies on the filename path being there, so I had to make sure `--with-filename` is being passed to `rg` to ensure that we get a filename path even when one file is searched.

**Comment by carlosflorencio** [comment]
Thanks for the quick fix :).

I was wondering the difference between setting the file with the `flags` vs the `filesFilter` property, and realized it would be cool to see the full final `rg` command with all the flags.

Thanks again

**Comment by MagicDuck** [comment]
np 😄 
`filesFilter` is just a shortcut for `--glob=<filesFilter>`
Unfortunately, `--glob` does not seem to like it when passing an absolute path as the filter, so that's why the README.md file suggests adding it to `Flags`.

Agreed on seeing the full `rg` command. I am just not sure how to expose it yet. Maybe we add a `debug=T/F` option?
I'll reopen this issue as a reminder while we think about it.

**Comment by carlosflorencio** [comment]
What about an option that we can toggle the visibility of the `rg` command inside the `grug-far` buffer? 

E.g pressing `,d` would toggle debug mode and display the `rg` command bellow the flags option.

**Comment by MagicDuck** [comment]
@carlosflorencio I've followed your suggestion and added it as `<localleader>p`
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/b5f83121-c394-4016-baad-bcb27dc4aea3">

The command displayed is shell escaped, so could be pasted into a terminal if needed.

**Comment by carlosflorencio** [comment]
Thanks @MagicDuck !
