### ISSUE TITLE
Wrap issue with help message

### ISSUE THREAD

**Issue by tednaaa** [MagicDuck/grug-far.nvim#116]
Thank you for such plugin! it's amazing

It is not a big issue, just some part of the help message hides if the buffer width is small

<img width="604" alt="image" src="https://github.com/user-attachments/assets/15d2c2f6-66fa-441a-aed2-d5e26119c152">

**Comment by MagicDuck** [comment]
Thanks for the kind words! :)
Hmm, for this issue, might be tough since it's virtual text and I don't believe that wraps...
I'll check when I get some time if there is any workaround, but am not super-optimistic about it 😆

**Comment by MagicDuck** [comment]
Yeah, `vim.api.nvim_buf_set_extmark()` does not do wrapping for virtual lines.

But you can disable / set placeholders like so:
https://github.com/MagicDuck/grug-far.nvim/blob/b902c852bb04f1daaa58a8454aad90b62ff227c9/lua/grug-far/opts.lua#L120

**Comment by MagicDuck** [comment]
Wait a sec, I just realized, are you actually talking about the help header?

<img width="657" alt="image" src="https://github.com/user-attachments/assets/8c22211f-7788-407a-b4d5-276fe752d4d7">

If yes, I have a plan to collapse that into a simpler `Press g? for help` or somesuch. It started out small, but we kept adding actions and it won't scale if we keep going like this, haha 😄

**Comment by tednaaa** [comment]
Thank you! actually, both 😄

I set enabled to false, it's ok for me, so will wait for keymap like `g?`

**Comment by MagicDuck** [comment]
@tednaaa Ok found a way to address both by listening to WinResized event. Check latest.
<img width="713" alt="image" src="https://github.com/user-attachments/assets/5d799d5c-ed3c-4d7e-9875-4278f2e21146">
