### ISSUE TITLE
[Bug] Keymap override doesnt unassign default map 

### ISSUE THREAD

**Issue by Ajaymamtora** [MagicDuck/grug-far.nvim#120]
If I override the close keymap like this:

```lua
...
    close = { n = '<C-c>q' },
...
```

'q' still closes the grug buffer. If I specify the close mapping in the setup it would make sense if the default doesnt get assigned

**Comment by MagicDuck** [comment]
Weird, `q` is not a default mapping at all ...
This works for me:
```lua
      require('grug-far').setup({
        keymaps = {
          close = { n = '<C-c>q' },
        },
      })
```
I even tried unsetting `localleader`, but still don't get the issue. 
Maybe you can inspect what's mapped with `:nmap q` and `:nmap <C-c>q`

<img width="740" alt="image" src="https://github.com/user-attachments/assets/8a32c799-63da-48a5-9725-f2900bc2a28d">

**Comment by MagicDuck** [comment]
@Ajaymamtora no worries, all good! 😄
