### ISSUE TITLE
Feature: disable search while typing/start search on leaving insert mode

### ISSUE THREAD

**Issue by marcomayer** [MagicDuck/grug-far.nvim#121]
Currently, you can only change debounceMs to not have a search fire too quickly. But when setting it too high, things feel laggy.

I think an option to only start the search when leaving insert mode would be amazing. Basically what spectre does.

**Comment by MagicDuck** [comment]
seems reasonable, I'll take a look when I get some time 😄

**Comment by MagicDuck** [comment]
@marcomayer FYI, option for this has been added
https://github.com/MagicDuck/grug-far.nvim/blob/74b779cc591c1e65133359297fb1c8a2ebad5cf9/lua/grug-far/opts.lua#L14
