### ISSUE TITLE
[BUG] long search lines scroll filters and flags

### ISSUE THREAD

**Issue by kapral18** [MagicDuck/grug-far.nvim#133]
https://github.com/user-attachments/assets/edee8d60-d892-4f38-ada4-a28276c25947

**Comment by MagicDuck** [comment]
interesting, I guess I never noticed this since I had `wrap` option set globally...
I guess it does make sense to turn it on by default for grug-far.nvim.

**Comment by MagicDuck** [comment]
Should be wrapping now! 😄
