### ISSUE TITLE
The error message takes over results

### ISSUE THREAD

**Issue by dinhtungdu** [MagicDuck/grug-far.nvim#145]
If `rg` has some error, Grug will clear the results and only display the error messages.

In my case, one of the `.gitignore` files in a subdirectory has a `{{slug.zip}}` pattern, which makes Ripgrep throw this error when parsing that file, and clear up the results

```
error parsing glob '{{slug}}.zip': nested alternate groups are not allowed
```

Instead of clearing the result, I think we should display both the result and the error in different sections.

**Comment by MagicDuck** [comment]
hmm, this is an open `rg` issue: 
https://github.com/BurntSushi/ripgrep/issues/1221

When running `rg` from the command line, does it still continue to work despite showing this error?
If yes, I think what we could do is provide some way to ignore it, since people can't really do anything about it for now, and it's just a visual distraction.

**Comment by MagicDuck** [comment]
showing those as warning messages for now, see https://github.com/MagicDuck/grug-far.nvim/pull/151 for now. We can think more about adding an option to ignore those as well...

<img width="1256" alt="image" src="https://github.com/user-attachments/assets/90aa5f57-a10a-48a3-89bd-c7d17fabaacb">

**Comment by dinhtungdu** [comment]
#151 tests well for me. Thanks so much for the quick updates.

An option to hide would be nice. In addition, can you consider adding an option to put the warnings at the bottom of the search results, or maybe set it as the default behavior. As we may have other warnings/errors that are helpful so I don't always want to hide them.

**Comment by MagicDuck** [comment]
no worries 😄 
> In addition, can you consider adding an option to put the warnings at the bottom of the search results, or maybe set it as the default behavior. As we may have other warnings/errors that are helpful so I don't always want to hide them.
If we put the warnings at the bottom, people won't see them ...

> An option to hide would be nice.
maybe what we do is some kind of "error filter" function that you can configure to whatever you'd like...

**Comment by MagicDuck** [comment]
actually, it looks like inserting it at the top at the end screws up treesitter higlighting.
So maybe what I'll end up doing is to put the warning at the end but include some sort of message in the header that it's there. That way maybe we don't even have to filter them.

**Comment by MagicDuck** [comment]
ok, moved it to then end and added a message about it 😄 
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/f0039ab2-e561-4c87-9a06-7b18424d43d4">

https://github.com/MagicDuck/grug-far.nvim/pull/153

**Comment by MagicDuck** [comment]
ok, will close for now just for issue management, but let me know if you run into any problem and I'll reopen 😄

**Comment by dinhtungdu** [comment]
Thank you so much, that's a great solution! Updated and it's working as expected.
