### ISSUE TITLE
FR:  supports `command-modifiers`  for `:GrugFar`

### ISSUE THREAD

**Issue by gh-liu** [MagicDuck/grug-far.nvim#152]
make grug-far buffer be opened `aboveleft` or `botright` the current window.

**Comment by MagicDuck** [comment]
already supported 😄, see this option https://github.com/MagicDuck/grug-far.nvim/blob/c5b4aab4dc4e7d10e77fd12324cd1a29441c0f15/lua/grug-far/opts.lua#L26

**Comment by MagicDuck** [comment]
oh do you mean like on the command itself?

**Comment by gh-liu** [comment]
yes, like run `:aboveleft GrugFar` to open the `grug-far` buffer in the left of current win.

**Comment by MagicDuck** [comment]
@gh-liu `command-modifiers` should now be supported 😄
