### ISSUE TITLE
A directory path in `Flags` appends extra text to files

### ISSUE THREAD

**Issue by mikavilpas** [MagicDuck/grug-far.nvim#154]
Just discovered something weird. If I replace some text in files and have the Flags field set to `.`, the replacing seems to append extra contents at the end of the file.

Reproduction script (run with `nvim -u repro.lua`):

<details><summary>Details</summary>
<p>

```lua
-- You can use this file to reproduce an issue with your configuration.

local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

-- install the following plugins
---@type LazySpec
local plugins = {
  'folke/tokyonight.nvim',
  {
    -- same initialization as in LazyVim
    -- https://github.com/LazyVim/LazyVim/blob/bcbab77f0c5851e6d73f275f2d27c3baa4f6aa68/lua/lazyvim/plugins/editor.lua#L130C1-L151C5
    'MagicDuck/grug-far.nvim',
    opts = { headerMaxWidth = 80 },
    cmd = 'GrugFar',
    keys = {
      {
        '<leader>sr',
        function()
          local grug = require('grug-far')
          local ext = vim.bo.buftype == '' and vim.fn.expand('%:e')
          grug.grug_far({
            transient = true,
            prefills = {
              filesFilter = ext and ext ~= '' and '*.' .. ext or nil,
            },
          })
        end,
        mode = { 'n', 'v' },
        desc = 'Search and Replace',
      },
    },
  },
}
require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

vim.cmd.colorscheme('tokyonight')
-- add anything else here
```

</p>
</details> 

I ran this and replaced with ` r` (space r)
![image](https://github.com/user-attachments/assets/8458bf9e-91e9-4cb0-b7ea-4eda36c3ab69)

It seems to add other files in the directory to the end 
![image](https://github.com/user-attachments/assets/1ad11135-2d57-44f7-b3af-ef0afa007a4a)

My global `.rgignore`
```text
.git
.oh-my-zsh/
node_modules
```

**Comment by MagicDuck** [comment]
So I ended up doing some thinking about this and due to the way things are structured for replace, the reliable way to make things work and also reduce confusion is to add another field, `Paths:` to the UI. Here is an example:

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/6ed9007c-fd78-411b-8295-a86747e959f9">

This change is now in!

You can fill that input with the `prefills.paths` option, and it can contain multiple paths. Also, it supports paths containing spaces with the following syntax: `./john\ doe/subdir/`

**Comment by mikavilpas** [comment]
Thanks, it seems to resolve this issue!

**Comment by MagicDuck** [comment]
great! Thanks for confirming!
