### ISSUE TITLE
Request for Collapsible Search Results

### ISSUE THREAD

**Issue by ian-ie** [MagicDuck/grug-far.nvim#166]
Hello, while using grug-far, I noticed that the search results display a large amount of information, making it somewhat visually cluttered. I would like to suggest adding a feature to collapse search results, allowing users to expand and collapse specific content as needed. This would greatly enhance the readability and user experience. Thank you for your hard work, and I hope you consider this suggestion!

**Comment by choovick** [comment]
Do you mean like adding a fold per file? like in VSCode or idea, if there are multiple results you can fold single file.

Else you can just narrow down search using file/path filters.

**Comment by ian-ie** [comment]
> Do you mean like adding a fold per file? like in VSCode or idea, if there are multiple results you can fold single file.
> 
> Else you can just narrow down search using file/path filters.

yes！like vscode

**Comment by MagicDuck** [comment]
I think we can do something here, although the nvim fold API is sort of garbagio 😆 

Need some feedback. What do you think of the following? I think the second one, where the file name is not part of the fold looks a bit better, right?
Although I don't use folds at all so I might be wrong here and the first one is the more practical usage wise.
The idea is that you would use those with the regular fold `z...` keybindings and we would have an option that would control whether we auto-fold immediately on search or not.

<img width="1142" alt="image" src="https://github.com/user-attachments/assets/68f43cba-5150-4d31-a300-c89038ec92e4">

<img width="1252" alt="image" src="https://github.com/user-attachments/assets/76ec5a2c-ee4d-4fd6-abc2-0b73c408d4cb">

**Comment by choovick** [comment]
I vote for option 2, as it is more informative, and contains at least one search query result. Would be amazing if this will work with standard z... keybindings. Less api to write this way (not an expert)?

**Comment by MagicDuck** [comment]
added foldcolumn as well to make it more obvious that there are folds there:
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/0aaf33d4-5ef0-409f-a001-efaaf7b7b3cb">

Implemented the following options:
```lua
  -- folding related options
  folding = {
    -- whether to enable folding
    enabled = true,

    -- sets foldlevel, folds with higher level will be closed.
    -- result matche lines for each file have fold level 1
    -- set it to 0 if you would like to have the results initially collapsed
    -- See :h foldlevel
    foldlevel = 1,

    -- visual indicator of folds, see :h foldcolumn
    -- set to '0' to disable
    foldcolumn = '1',
  },
```

@ian-ie so for your case, just call grug-far with `folding.foldlevel = 0`

**Comment by ian-ie** [comment]
Thank you for your help, but as a beginner, I'm encountering an error with lazyvim when I try 'za' – it says 'not fold'. Even after executing 'set foldlevel=1', 'zm' doesn't seem to respond.

**Comment by ian-ie** [comment]
Thank you! Now it's working just as I had hoped!
