### ISSUE TITLE
Invalid window id from nvim_win_set_cursor

### ISSUE THREAD

**Issue by lucasrabiec** [MagicDuck/grug-far.nvim#168]
I am getting an error while trying to open GrugFar only for .js, .ts and .tsx files.
Grug opens but not in the split pane (what happens for other file's extensions) and shows the following error:
```
Error executing vim.schedule lua callback: ...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:298: Invalid window id: 1012
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:298: in function <...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:284>

```
I am using the newest LazyVim with nvim 0.10.1

**Comment by MagicDuck** [comment]
hmm, I just tried it myself and it worked fine for a `.tsx` file. While I don't use `LazyVim`  but my own handrolled config, I did copy the LazyVim suggested config:
```
  {
    'MagicDuck/grug-far.nvim',
    opts = { headerMaxWidth = 80 },
    cmd = 'GrugFar',
    keys = {
      {
        '<leader>sr',
        function()
          local grug = require('grug-far')
          local ext = vim.bo.buftype == '' and vim.fn.expand('%:e')
          grug.grug_far({
            transient = true,
            prefills = {
              filesFilter = ext and ext ~= '' and '*.' .. ext or nil,
            },
          })
        end,
        mode = { 'n', 'v' },
        desc = 'Search and Replace',
      },
    },
  },

```

There is nothing there ☝️ specific to those types of files, so I think the problem might be some LSP stuff (vtsls?) or autocommand related to these types of files. I would suggest filing an issue with lazyvim itself.

**Comment by MagicDuck** [comment]
I've wrapped the `nvim_win_set_cursor` call with `pcall` meanwhile in case that helps to tide you over meanwhile

**Comment by lucasrabiec** [comment]
I found out what was causing the problem. The lsp config:
```lua
opts = {
    servers = {
      eslint = {
        on_attach = function(_, bufnr)
          vim.api.nvim_create_autocmd({ "BufWritePre", "BufLeave", "WinLeave", "FocusLost" }, {
            buffer = bufnr,
            command = "EslintFixAll",
          })
        end,
        root_dir = require("lspconfig.util").find_git_ancestor,
      },
   },
}
```
It is "BufLeave" autocmd. Any ideas what I can do without removing BufLeave?

**Comment by MagicDuck** [comment]
What’s the exact error you are getting with latest version of the plugin? Asking since line numbers have likely changed.

**Comment by MagicDuck** [comment]
actually weird, the error at the very top says `nvim_win_set_cursor` and there is only one such call in that file, the one I wrapped with `pcall` when you initially reported this:
```
    pcall(vim.api.nvim_win_set_cursor, win, { context.options.startCursorRow, 0 })
``` 
So am not sure how you are still getting an error from there unless you haven't updated?

**Comment by MagicDuck** [comment]
hmm, interesting...
My guess is that the current logic to create the grug-far window with `vim.cmd(context.options.windowCreationCommand)` is broken by having an event interpose as it becomes somewhat async when the window will be available.
I'll try to create a PR switching from that to using the window open api:
```
lua vim.api.nvim_open_win(0, true, {vertical=true})
```
and see if it addresses the issue.

**Comment by MagicDuck** [comment]
@lucasrabiec actually, I tried your config with `EslintFixAll` and I don't get an issue. But if I change the command to a callback from which I error out, then I get weird behaviour.
Can you try what happens when you change to:
```
            command = "silent! EslintFixAll",
```

**Comment by lucasrabiec** [comment]
There is no error or warning but it still opens grug on the entire window. As a workaround, I just deleted "BufLeave" from the config.

**Comment by MagicDuck** [comment]
The only other thing I can think of is to mess with https://github.com/MagicDuck/grug-far.nvim/blob/27a502037da8657a8b2ab7e31a6439d7b7063af5/lua/grug-far/opts.lua#L117 option.
Maybe set it to “vertical edit %”?
Sorry, out of ideas … I don’t think my previous one to use the lua api would make much of a difference.
I guess something is killing the split but dunno what since I cannot repro.

**Comment by MagicDuck** [comment]
Since there is nothing to do for now, I will close the issue.
