### ISSUE TITLE
Error when opening GrugFar in LazyVim

### ISSUE THREAD

**Issue by Hexdigest123** [MagicDuck/grug-far.nvim#174]
Hello, I am currently facing an issue when opening Grug-far: I get an error spam that you can see below, along with some additional information about my config.

LazyVim Information:

NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634

Healthcheck:
- OK rg: found ripgrep 14.1.0

Error Log from LazyVim:

Error detected while processing WinResized Autocommands for "*":
Error executing lua callback: ...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:259: attempt to call field 'iter' (a nil value)
stack traceback:
	...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:259: in function <...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:258>
Error detected while processing WinResized Autocommands for "*":
Error executing lua callback: ...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:259: attempt to call field 'iter' (a nil value)
stack traceback:
	...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:259: in function <...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:258>

**Comment by MagicDuck** [comment]
ah, that looks like it's complaining about `vim.iter` which was introduced in `nvim 0.10`. Can you upgrade your nvim? We need to up the version check ...

**Comment by MagicDuck** [comment]
I've bumped the version check, sorry for the trouble! 😄
