### ISSUE TITLE
feature(icons): Add file path icon on search result pane

### ISSUE THREAD

**Issue by jugarpeupv** [MagicDuck/grug-far.nvim#182]
Hi,

thank you for this amazing plugin, i thought it would be awesome to see the icon of the file at the beginning, i guess it shoult no be very difficult to implement

I will try to implement it when i got some spare time

**Comment by MagicDuck** [comment]
Great, let me know if you have any questions on where stuff is in the code 😄 
Also we should make it optional as it will introduce a dependency on nvim-devicons or mini.icons.

**Comment by MagicDuck** [comment]
added support for icons 😄
