### ISSUE TITLE
User-friendly changelog

### ISSUE THREAD

**Issue by b1nhack** [MagicDuck/grug-far.nvim#183]
When lazy.nvim checks for updates, grug-far.nvim has dozens of commits, and I have to spend time checking them one by one. Consider using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), or some other user-friendly changelog.

**Comment by MagicDuck** [comment]
Why do you have to check each commit?
Sorry, I am not changing the way I do commits. I do them like I do cause they help me isolate work.

You can check the pull requests lost if you want a list with better titles of what happened…
