### ISSUE TITLE
Disable the setting that lets backspace go onto previous lines in the plugin buffer

### ISSUE THREAD

**Issue by srcrip** [MagicDuck/grug-far.nvim#19]
As the title says, there's a setting that enables this that I think should probably be toggled off when you enter the plugins buffer. That way if you hold down the backspace key while in insert mode in one of the sections, to clear that section, it doesn't automatically go clear one of the others when your cursor wraps around to the previous line.

**Comment by MagicDuck** [comment]
That’s a clever idea. Am assuming you are talking about this one
https://vimhelp.org/options.txt.html#%27backspace%27
i had forgotten this existed, haha. Will do

**Comment by MagicDuck** [comment]
thanks for bringing this up, as it was one of the sort of annoying things.
You can now delete like a boss 😆   
https://github.com/MagicDuck/grug-far.nvim/pull/21
