### ISSUE TITLE
AST - document for URI could not be found..

### ISSUE THREAD

**Issue by JoseConseco** [MagicDuck/grug-far.nvim#197]
I get this error message:
```
RPC[Error] code_name = InvalidParams, message = "Document for URI could not be found: file:///home/bartosz/.config/blender/4.2/extensions/user_default/blob_fusion/Grug%20FAR%20-%208%3A%20duplicate_node_exact%20%24, URIs of the known document are: file:///home/bartosz/.config/blender/4.2/extensions/user_default/blob_fusion/blob_utils.py, file:///home/bartosz/.config/blender/4.2/extensions/user_default/blob_fusion/Grug%20FAR%20-%208"
```
When performing search with AST grep:
![image](https://github.com/user-attachments/assets/32f4e608-f789-4613-827f-94d1acfd1a00)
When running ast-grep from terminal- it works ok:
![image](https://github.com/user-attachments/assets/869405c1-193f-4cf0-a40c-45aef2c785ac)

Any idea what could be wrong?
My config:
```lua
      require('grug-far').setup({
        engines = {
          astgrep = { path='ast-grep'},
        },
        engine = 'astgrep',
        folding={enabled=false},
      });
lua

**Comment by MagicDuck** [comment]
I think the error is most likely coming from copilot. You can exclude the grug-far filetype from it. see:
https://github.com/MagicDuck/grug-far.nvim/issues/93

Regarding the `no matches` part. I see that in the terminal you don't have braces "()" at the end of your expression, could that be the difference?

**Comment by JoseConseco** [comment]
Thanks for reply. The bracket - with or without does not make the difference.  
I tried to disable the copilot but it does not seem to change anything (I assume the filetype - mask supposed to go into copilot config?). In any case even with copilot disabled still nothing would show up. 
But now even message is gone. So no result for search, and no error. .

**Comment by MagicDuck** [comment]
Yeah, it's sort of weird, I just tried it and I could not get it to work even in CLI:
<img width="974" alt="image" src="https://github.com/user-attachments/assets/bf2e6608-b950-40c3-9a7f-d2c3d8fc4003">

**Comment by JoseConseco** [comment]
@MagicDuck  for me after all the issue is only with astgrep - and  space.  Like I have funciton:

def text(something)

And 'def' input will list all  entries correctly. But  'def ' - nothing will show. And error from first post is shown:

```
RPC[Error] code_name = InvalidParams, message = "Document for URI could not be found: file:///home/bartosz/.config/blender/scripts/addons/blob_fusion/Grug%20FAR%20-%209%3A%20df, URIs of the known document are: file:///home/bartosz/.config/blender/scripts/addons/blob_fusion/blob_ui.py, file:///home/bartosz/.config/blender/scripts/addons/blob_fusion/Grug%20FAR%20-%209"

```
Im not sure where  `Grug%20FAR%20-%209` comes from, but I think it gives the error.

**Comment by MagicDuck** [comment]
the `Grug%20FAR%20-%209` stuff is just the name of the buffer (gets updated with the search you type in)
grug-far does not do any RPC though. It's must be a language server or some other plugin that does RPC.
If you do `:LspInfo` while inside the grug-far buffer, do you see anything attached?

**Comment by JoseConseco** [comment]
Just the copilot, but I tried to disable it and nothing chaged.
![image](https://github.com/user-attachments/assets/f9b4f224-ffd4-43d5-bd10-15be34afb398)

Will try again in sec.

**Comment by MagicDuck** [comment]
Just tried the latest release and I get nothing. When I tried the `def $A` pattern in their playground it says it's an error:
https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiamF2YXNjcmlwdCIsInF1ZXJ5IjoiZGVmICRNQVRDSCgpIiwicmV3cml0ZSI6ImxvZ2dlci5sb2coJE1BVENIKSIsInN0cmljdG5lc3MiOiJzbWFydCIsInNlbGVjdG9yIjoiIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmxvZygkQSlcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUuZGVidWcoJEEpXG5maXg6XG4gIGxvZ2dlci5sb2coJEEpIiwic291cmNlIjoiZGVmIGludHJvZHVjdGlvbihuYW1lKTpcbiAgICBcIlwiXCJJbnRyb2R1Y2VzIGEgcGVyc29uIGdpdmVuIHRoZWlyIG5hbWVcIlwiXCJcbiAgICBwcmludCgnSGVsbG8hIE15IG5hbWUgaXMnLCBuYW1lKVxuXG5kZWYgaGVsbG8obmFtZSk6XG4gICAgXCJcIlwiQmxhaCBhIHBlcnNvbiBnaXZlbiB0aGVpciBuYW1lXCJcIlwiXG4gICAgcHJpbnQoJ0hlbGxvISBNeSBuYW1lIGlzJywgbmFtZSkifQ==

**Comment by MagicDuck** [comment]
> Still no results but at least no error.... so maybe there are two issues. Let me know if updating astgrep changed anything for u.
Yeah, it's 2 separate issues, but this verifies that copilot is causing that error message to show up.

**Comment by MagicDuck** [comment]
this way of matching it did work though:
<img width="1513" alt="image" src="https://github.com/user-attachments/assets/1a0e5492-7565-4d78-9b46-c2f9b5c9dec2">

**Comment by JoseConseco** [comment]
ok, I think the issue was  that I just did not understand ast correctly (+ copilot issue). Closing this then.
