### ISSUE TITLE
ignoreVisualSelection does not work

### ISSUE THREAD

**Issue by WizardStark** [MagicDuck/grug-far.nvim#198]
### Repro code
I wanted to change the behaviour of grug far when running with a visual selection, with the following snippet:

```lua
local text = require("user.utils").region_to_text(vim.region(0, "'<", "'>", vim.fn.visualmode(), true))
text = "(" .. text:gsub("\n%s+", "\n"):gsub("(\n)$", ""):gsub("[\n\r]", "\\n)(.*") .. ")"
require("grug-far").grug_far({
    ignoreVisualSelection = true,
    prefills = {
        search = text,
        flags = "-U",
    },
})
```

with the following for `require("user.utils").region_to_text`

```lua
function M.region_to_text(region)
	local text = ""
	local maxcol = vim.v.maxcol
	for line, cols in vim.spairs(region) do
		local endcol = cols[2] == maxcol and -1 or cols[2]
		local chunk = vim.api.nvim_buf_get_text(0, line, cols[1], line, endcol, {})[1]
		text = ("%s%s\n"):format(text, chunk)
	end
	return text
end
```

For what its worth, this is the setup function for grug-far, as I was not sure from reading the docs whether default ops meant grug-far defaults, or the defaults as they are after merging the setup spec (I assume the latter, but tried this as a last resort):
```lua
require("grug-far").setup({
    ignoreVisualSelection = true,
})
```
### Expectation
A grug-far window should open, with the search prefilled with my formatted text, with *only* the `-U` flag.

### What actually happens
A grug-far window opens, with the builtin visual selection handling and `-U --fixed-strings` as flags.

Plugin info from lazy.nvim (for version purposes):
```
        url  https://github.com/MagicDuck/grug-far.nvim
        branch main
        commit 1af4db8
        readme README.md
        help   |grug-far.txt|
```

**Comment by MagicDuck** [comment]
hmm, weird, this just worked for me with a visual selection:
```
:lua require("grug-far").grug_far({ ignoreVisualSelection = true, prefills = { search = "mytext", flags = "-U" } })
```

**Comment by MagicDuck** [comment]
also, tried this snippet based on your code:
```lua
      local grugFar = require('grug-far')
      grugFar.setup({})

      local function region_to_text(region)
        local text = ''
        local maxcol = vim.v.maxcol
        for line, cols in vim.spairs(region) do
          local endcol = cols[2] == maxcol and -1 or cols[2]
          local chunk = vim.api.nvim_buf_get_text(0, line, cols[1], line, endcol, {})[1]
          text = ('%s%s\n'):format(text, chunk)
        end
        return text
      end

      vim.keymap.set('n', '<leader>so', function()
        local text = region_to_text(vim.region(0, "'<", "'>", vim.fn.visualmode(), true))
        text = '(' .. text:gsub('\n%s+', '\n'):gsub('(\n)$', ''):gsub('[\n\r]', '\\n)(.*') .. ')'
        require('grug-far').grug_far({
          ignoreVisualSelection = true,
          prefills = {
            search = text,
            flags = '-U',
          },
        })
      end)
```

and that seemed to work:
<img width="2053" alt="image" src="https://github.com/user-attachments/assets/025b5d9d-2029-46ef-ac45-8eaddfc6cb5e">

**Comment by MagicDuck** [comment]
ah, nvm, that should be `  vim.keymap.set('v'`. I see the problem now! 👍

**Comment by MagicDuck** [comment]
lua ternary tricked me, lol. Ok, should be fixed now.
This is the code that worked for me:
```lua
      local grugFar = require('grug-far')
      grugFar.setup()

      local function region_to_text(region)
        local text = ''
        local maxcol = vim.v.maxcol
        for line, cols in vim.spairs(region) do
          local endcol = cols[2] == maxcol and -1 or cols[2]
          local chunk = vim.api.nvim_buf_get_text(0, line, cols[1], line, endcol, {})[1]
          text = ('%s%s\n'):format(text, chunk)
        end
        return text
      end

      vim.keymap.set('v', '<leader>so', function()
        vim.cmd([[normal! vv]])
        local text = region_to_text(vim.region(0, "'<", "'>", vim.fn.visualmode(), true))
        text = '(' .. text:gsub('\n%s+', '\n'):gsub('(\n)$', ''):gsub('[\n\r]', '\\n)(.*') .. ')'
        require('grug-far').grug_far({
          ignoreVisualSelection = true,
          prefills = {
            search = text,
            flags = '-U',
          },
        })
      end)

``` 

Note that I had to throw the following in there for it to work, but in any case the option is respected now 😄 :
```lua
        vim.cmd([[normal! vv]])
```

**Comment by MagicDuck** [comment]
closing for issue management purposes, but feel free to reopen if you still see the problem 😄

**Comment by WizardStark** [comment]
Perfect, working on my end! Now I just need to actually escape reserved characters in the selected text for that binding to be useful 😆. Thanks for the swift response!

**Comment by MagicDuck** [comment]
No problem! :)

**Comment by MagicDuck** [comment]
@WizardStark FYI, mentioning since you were doing something similar. Since a lot of people seem to want to do multline searches based on visual selection, I changed the UI inputs somewhat to allow for entering multiline input. So stuff like this works out of the box now:

<img width="2498" alt="image" src="https://github.com/user-attachments/assets/b52983bd-2192-4073-b507-e622081d2edd">
