### ISSUE TITLE
if I launch GrugFar a blank page is opened and only once I enter insert mode it shows ui

### ISSUE THREAD

**Issue by MagicDuck** [MagicDuck/grug-far.nvim#2]
[Crivotz](https://www.reddit.com/user/Crivotz/)
•
[4m ago](https://www.reddit.com/r/neovim/comments/1co755r/comment/l3ei94s/)
set expandtab
is it normal that if I launch GrugFar a blank page is opened and only once I switch to Insert mode and press a character is the real screen shown?

**Comment by MagicDuck** [comment]
ok I still can't see it, but since it was quick, I made a change to render immediately as well in addition to on text change event, so hopefully that should fix it.

**Comment by crivotz** [comment]
Solved, thanks

**Comment by MagicDuck** [comment]
perfect, thanks for confirming! I'll close the ticket!
