### ISSUE TITLE
feat: add support to pass config option to `:GrugFar`

### ISSUE THREAD

**Issue by dhruvinsh** [MagicDuck/grug-far.nvim#209]
It would be good idea to allow to pass config option to `:GrugFar` command. 
That way don't have to call whole api command.

For example, 
`:lua require("grugfar.nvim").grug_far({engine="ripgrep"}` becomes `:GrugFar engine="ripgrep"`

**Comment by MagicDuck** [comment]
I am not willing to support this way of passing options as it entails parsing the arguments which is a pain and a lot of the grug-far.nvim options are non-string. 
I am willing to compromise a little bit though and provide `GrugFar <engine>`. Is that sufficient for your purposes?

**Comment by dhruvinsh** [comment]
Yes that make sense. I realized later that parsing all the option would be troublesome. 

> I am willing to compromise a little bit though and provide :GrugFar <engine>. Is that sufficient for your purposes?

Having just that option would be great. I usually look for engine changes only. And rest if the option still come from default/override option.

**Comment by MagicDuck** [comment]
change is in latest version 😄
