### ISSUE TITLE
Symlink support?

### ISSUE THREAD

**Issue by fritzblue** [MagicDuck/grug-far.nvim#211]
Many dotfile systems and other setups rely on symlinks to function correctly. I believe because `--follow` is [blacklisted](https://github.com/MagicDuck/grug-far.nvim/blob/f127553700b89790af7daaff0bf049e335fe3ac9/lua/grug-far/engine/ripgrep/blacklistedReplaceFlags.lua#L15) symlinks simply cannot be followed with grug-far.

Am I understanding that correctly? Is there any solution for following symlinks?

Thanks in advance!

**Comment by MagicDuck** [comment]
Just to confirm, you are seeing this issue on trying to replace, not the search itself, correct!
That being said I believe I may have been overzealous in adding that to the blacklist so we can likely remove it if it causes no issue.

**Comment by MagicDuck** [comment]
just checked it out, yeah it's only on replace and does not cause any issues. As such removing the restriction.
