### ISSUE TITLE
Smart replace (a.k.a preserve case)

### ISSUE THREAD

**Issue by fritzblue** [MagicDuck/grug-far.nvim#216]
Is there a way to intelligently replace matches while preserving their existing case?

For example replacing 'foo' with 'bar' in "foo Foo FOO", will result in "bar Bar BAR".

Here is a link to the [equivalent vscode feature](https://code.visualstudio.com/updates/v1_37#_preserve-case-in-find-and-replace) for reference.

**Comment by MagicDuck** [comment]
Not directly through ripgrep unless there is some option I am missing.
What you can do though ism
1. do case insensitive search for say ‘foo’
2. Use something like https://github.com/tpope/vim-abolish#substitution to do your desired case preserving replace in the grug far buffer
3. Trigger the Sync All action

**Comment by fritzblue** [comment]
Makes sense. Just realized [text-case.nvim](https://github.com/johmsalas/text-case.nvim) has `:Subs` for this, which works great. Thanks!
