### ISSUE TITLE
Feature: improve searchOnInsertLeave

### ISSUE THREAD

**Issue by marcomayer** [MagicDuck/grug-far.nvim#222]
Currenty when `searchOnInsertLeave = true` is set in the options, there's a refresh when leaving insert mode. But there's no refresh on other changes like going over a char and typing `rX` to change the char under the cursor to X.

So ideally it would trigger on any such changes but not while in insert mode. Of course the options flag might need a new name then. If I find some time I'll come up with a PR myself but not sure when 🤷

**Comment by MagicDuck** [comment]
Good idea! Should be easy to do, just need to alert people option name has changed if we want to keep it as one option.

**Comment by MagicDuck** [comment]
implemented it, but could not think of a better name for the option, so just stayed with it 😆

**Comment by MagicDuck** [comment]
feel free to reopen if you see any issue! 😄
