### ISSUE TITLE
[Help] Support multiple globs for the files filter

### ISSUE THREAD

**Issue by Ajaymamtora** [MagicDuck/grug-far.nvim#227]
I'm trying to pass in a ripgrep set of globs for file filters.

For example, in the screenshot below I'm trying to include `.lua` and `.toml` and exclude the `.git` folder, but adding the exclusion for the git folder breaks the search. This is possible if I could provide 2 globs e.g. `rg --glob '*.{lua,toml}' --glob '!.git/*' -- nvim`

![image](https://github.com/user-attachments/assets/63e836c6-4ee0-471d-9cbb-ef6350f138c6)

A potential solution could be to split the files filter into 2 section, 1 called Include files filter, the other Exclude files filter. This seems the cleanest and easiest to use.

You could also somehow update the current files filter to allow the user to define 2 globs?

I know I could continue to just use the flags and pass the glob below in the flags section, but it's im trying to filter files so would rather use its designated section.

I have a binding that opens grug with my telescope grep state:
![image](https://github.com/user-attachments/assets/2a148d1c-d429-4c05-ba9c-bbe0c4f7b0b8)

**Comment by MagicDuck** [comment]
Hi @Ajaymamtora ,
I suppose we could support multiple globs in files filter by having one glob per line.
Would that help? Given the amount of globs you have in the screenshot, it might just be better o continue using the Flags input…

**Comment by MagicDuck** [comment]
Hi @Ajaymamtora,

One glob per line should work in latest now 😄 
<img width="1260" alt="image" src="https://github.com/user-attachments/assets/09d2a56f-09a9-4860-9f9a-f4d4d42a1393">
