### ISSUE TITLE
feature: gotoLocationAndClose

### ISSUE THREAD

**Issue by fresh2dev** [MagicDuck/grug-far.nvim#236]
Me like Grug. Me like to use Grug to find needle in haystack. When I find needle, I close Grug.

I would be nice to <C-enter> on an entry, jump to it, and close Grug. Like the opposite of `openLocation`.

```
gotoLocation = { n = '<enter>' },
gotoLocationAndClose = { n = '<C-enter>' },
```

**Comment by MagicDuck** [comment]
haha, that gave me a chuckle 😄 
You can already achieve that like so:
```lua
vim.api.nvim_create_autocmd('FileType', {
  group = vim.api.nvim_create_augroup('grug-far-keybindings', { clear = true }),
  pattern = { 'grug-far' },
  callback = function()
    vim.api.nvim_buf_set_keymap(0, 'n', '<C-enter>', '<localleader>o<localleader>c', {})
  end,
})
```
I try as much as much as possible to just provide the building blocks in terms of actions as there are many combinations they can be used in.

**Comment by MagicDuck** [comment]
added it to Cookbook in README

**Comment by fresh2dev** [comment]
Love it! This works; thank you 🙏
