### ISSUE TITLE
Error when trying to call grug-far open

### ISSUE THREAD

**Issue by dudicoco** [MagicDuck/grug-far.nvim#250]
I'm attempting to run the following in my nvim cmd:
```lua
lua require('grug-far').open()
``` 

This gives me the following error:
```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'open' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

```
nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
```

**Comment by MagicDuck** [comment]
hi @dudicoco , I don't see that myself locally and the `.open()` API is also exercised by unit tests, so I think the problem might be with how you are loading the plugin or you are on an older version of `grug-far` before `.open()` was added. Try to update.

**Comment by dudicoco** [comment]
updating to the latest version fixed the issue (even though I was already on a pretty recent version), thanks.
