### ISSUE TITLE
Add possibility to modify the replacement string

### ISSUE THREAD

**Issue by Groz17** [MagicDuck/grug-far.nvim#251]
Similar to how in Vim you can type `\=` to interpret the replacement as an expression, it would be cool if you could the same with this plugin.

For example, using ripgrep the various `submatch(0)`, ..., `submatch(n)` would be `$0`, ..., `$n`.

This behaviour would be triggered by a map, like `<localleader>x`, where x stands for e**x**pression.

You could use vimscript string-related functions like `substitute()`, `repeat()`, etc...

I'm not sure if this is even possible considering you're using external commands, but it's something that could be potentially useful.

Thanks for the plugin btw, it looks amazing!

**Comment by Groz17** [comment]
Yes, you understood perfectly.

I hadn't thought about using a function, that looks pretty neat. This would suggest Lua to be the default language choice, and iirc you could still use something like `vim.api.nvim_eval` to evaluate vimscript expressions.

I think, at least for the moment, that just having `$0` to manipulate would already be magnificent.

I guess in this mode the results would update at every `CursorMoved` event (`CursorMovedI` event seems too much since you first need to build/return an expression).

**Comment by MagicDuck** [comment]
> I guess in this mode the results would update at every TextChanged event (TextChangedI event seems too much since you first need to build/return an expression).
That’s a great idea! Grug-far already supports normal mode only search, so we can switch to that modality and indicate it somewhere in the UI, potentially next to the engine.

Note that it might be a while before I can work on this depending on how I get time. Should be a fun one to implement though :)

**Comment by MagicDuck** [comment]
@Groz17 okie, took a lot of doing, but it's finally here 😄 

Both lua and vimscript "interpreters" are supported. Press `<localleader>x` to switch.
In astgrep engine, you also have access to the meta variables:

<img width="1257" alt="image" src="https://github.com/user-attachments/assets/81bac7ab-7c80-43ba-96db-c834992fbe79">

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/732f0b0e-4a05-4eb2-bf99-9a9c8530c042">

**Comment by MagicDuck** [comment]
feel free to reopen if you see any issue 😄

**Comment by Groz17** [comment]
This is absolutely fantastic, congratulations! 🥳 
The treesitter highlight is a nice touch as well :D

This also allows to use external commands to modify the replacement string, which makes this plugin really stand out!

![Functions](https://github.com/user-attachments/assets/ecf1af73-f528-4f66-9741-7251199bf95f)

**Comment by MagicDuck** [comment]
Thank you very much! 😄 
That's a really cool usage I haven't thought about. It always amazes me in a good way what shapes people have yoga-twisted this plugin in, haha.
