### ISSUE TITLE
Error `Duplicate tag "grug-far.setup()"` when updating via lazy.nvim

### ISSUE THREAD

**Issue by chrisgrieser** [MagicDuck/grug-far.nvim#26]
```
...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:84: Vim:E154: Duplicate tag "grug-far.setup()" in file /Users/chrisgrieser/.local/share/nvim/lazy/grug-far.nvim/doc//grug-far.txt
```

I tried uninstalling and reinstalling the plugin, the error seems to persist. This is the only plugin this error occurs with. I have `readme.enabled = false` in my lazy config, so it's not related to lazy's doc creation.

**Comment by MagicDuck** [comment]
Ah that looks like it might be the duplicate help tag here
https://github.com/MagicDuck/grug-far.nvim/blob/c7c4285c28c280da5ceb0cb64eb6731f7a30cb18/doc/grug-far.txt#L46
Didn’t know help docs could have such an effect, haha

**Comment by MagicDuck** [comment]
fixed in https://github.com/MagicDuck/grug-far.nvim/pull/28

**Comment by MagicDuck** [comment]
lemme know if you still see any issues and I'll reopen

**Comment by chrisgrieser** [comment]
Works fine now - thanks!
