### ISSUE TITLE
Characters disappear after typing when searching and require to be pressed twice when replacing

### ISSUE THREAD

**Issue by RAV64** [MagicDuck/grug-far.nvim#264]
Hi - What an title :'D I decided to fit these into singular issue since I could not find others having either of these problems so I believe they might have the same cause.

In both scenarios I open my grug-far window with the keybinding visible on the video ("<leader>sr" in normal mode. I've bound <leader> to space) with only option being "transient = true"

First - When typing a search query - On a regular interval the characters automatically delete themselves while I stay on the search query line (In either insert/normal mode at least). If I switch to and back to the search query line, the disappearing stops.

https://github.com/user-attachments/assets/0999204d-cf7a-4e94-bd49-f0042cc02fcc

Second - When writing a replacement query - I need to press each letter TWICE for it to register.. If I input any other letter as the second pair, that one becomes the new letter that needs to be pressed once more for it to register. In the example video the input string I'm writing is "1122345567" which results in "125" being written as the search query.

https://github.com/user-attachments/assets/ffeceecb-a65d-4f8f-a0c7-bd76b1e5a89c

Please let me know what further information I can provide relating to this ~

**Comment by MagicDuck** [comment]
Wow, that's super messed up! 😆 
grug-far does not have code that would delete characters like that to my knowledge.
Only thing it deletes is the lines in the results area.
My guess is that there's something in your config, like some autocommand, that's causing this.

To isolate the problem, can you try to save the following to a `repro.lua` file and run it with:
```
nvim -u NORC -l repro.lua
```
Then run grug-far with `<leader>sr` and see if you can reproduce the problem.

`repro.lua`:
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
-- local lazypath = vim.fn.expand("~/projects/plugins/lazy.nvim/")
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

vim.opt.statuscolumn = "1"

vim.g.mapleader = " "
vim.g.maplocalleader = ","

-- install plugins
local plugins = {
  { "folke/tokyonight.nvim" },

  {
    dir = "/opt/repos/grug-far.nvim",
    name = "grug-far",
    opts = { headerMaxWidth = 80 },
    cmd = "GrugFar",
    keys = {
      {
        "<leader>sr",
        function()
          local grug = require("grug-far")
          local ext = vim.bo.buftype == "" and vim.fn.expand("%:e")
          grug.open({
            transient = true,
          })
        end,
        mode = { "n", "v" },
        desc = "Search and Replace",
      },
    },
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by RAV64** [comment]
Unfortunately I'm not able to run the repro.lua file with the instructions you have provided. After saving the file and running `nvim -u NORC -l repro.lua` Neovim doesn't start.

I've reproduced this with multiple nightly and 0.10.1 - Haven't tried older versions.

I've managed to binary search the issue on my configuration and the functionality I've described can be enabled by adding the following line `vim.keymap.set("n", "z", vim.diagnostic.goto_next, { desc = "Goto next diagnostics" })` while commenting it out results in expected behavior. Super strange 😅

**Comment by RAV64** [comment]
Adding to previous - `vim.keymap.set("n", "z", function() end)` is enough to trigger this behavior.

I don't know if this is related but sometimes when I close grug-far I get this error message.

```
Error executing vim.schedule lua callback: ...m/lazy/grug-far.nvim/lua/grug-far/render/resultsList.lua:304: Invalid buffer id: 263
stack traceback:
        [C]: in function 'nvim_buf_get_extmarks'
        ...m/lazy/grug-far.nvim/lua/grug-far/render/resultsList.lua:304: in function 'markUnsyncedLines'
        ...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:325: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

This might be just a result of the behavior we observe? I haven't been able to repro this error when I've not bound "z" in normal mode... 🤣

**Comment by RAV64** [comment]
I've solved this by constraining the keymap to a buffer since I'm already calling this in LspAttach autocmd

```
vim.api.nvim_create_autocmd("LspAttach", {
	group = vim.api.nvim_create_augroup("user-lsp-attach", { clear = true }),
	callback = function(event)
		local set = function(mode, keys, func, desc)
			vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = desc })
		end
		set("n", "z", vim.diagnostic.goto_next, "Goto next diagnostics")
	end,
})
```

With this I no longer get the strange behavior.

There is still definitely something fishy which caused the behavior to begin with..

**Comment by MagicDuck** [comment]
Ah very interesting. I think this is related to calling zx to update results folds on search.

https://github.com/MagicDuck/grug-far.nvim/blob/308e357be687197605cf19222f843fbb331f50f5/lua/grug-far/fold.lua#L20

 But since you rebind z, it probably ends up just doing x which deletes chars. Unfortunately nvim does not provide any api to update folds. An alternate fix is to disable folding with folding.enable = false option.

**Comment by MagicDuck** [comment]
Related nvim issue: 
https://github.com/neovim/neovim/issues/19226

**Comment by dstein64** [comment]
I came across this issue since I'm subscribed to https://github.com/neovim/neovim/issues/19226.

Changing `normal zx` to `normal! zx` could be another way to resolve the issue, since the `!` would prevent the mapping from being used.

**Comment by MagicDuck** [comment]
@dstein64 thank you so much for taking the time to mention this! I did not know about that behaviour.
Seems like a simple fix to make then! :)

**Comment by MagicDuck** [comment]
@RAV64 made the change to use `normal!`. Feel free to reopen if you still see the issue.
