### ISSUE TITLE
README: Replace ellipses with Lua comments in installation example

### ISSUE THREAD

**Issue by noornee** [MagicDuck/grug-far.nvim#266]
## Appreciation
Hellooo, I just discovered `grug-far.nvim` today from your [reddit post](https://www.reddit.com/r/neovim/comments/1fl2i8t/grugfarnvim_update_file_icons_replacement_diff/) and decided to try it out.
I find myself doing a lot of search and replace lately and this plugin totally satisfies my needs. Thanks for the amazing work! its super awesome and im loving it!

# issue
while i copy-pasted the the installation example for `lazy.nvim` from the README, i noticed that the example includes ellipses (`...`) where lua comments (`--`) should be. I had to manually comment out the description text which was a bit "stressful" :D

I plan to resolve this issue by opening a PR myself. thanks again!

**Comment by MagicDuck** [comment]
Thank you for the kind words, @noornee 
You are right, it does make sense to comment those out for easy copy/paste 😄
