### ISSUE TITLE
Buffer Pollution in Result Preview

### ISSUE THREAD

**Issue by kah-ell** [MagicDuck/grug-far.nvim#268]
Great plugin, thank you!

If you browse in normal mode through the search results, every buffer for the file/match preview remains in the buffer list. This results in a potentially enormous number of buffers listed in plugins like 'BufferLine', for instance.

It would be great if after the preview, the buffer is deleted or wiped. (or nuked from orbit, the only way to be sure)

Thank you for your time. :)

**Comment by MagicDuck** [comment]
I've thought about this issue, but I am not sure what the right solution is yet...
Reason is cause after people shuffle through matches, they might use a window navigation command like `<C-w>h` to switch over to the last previewed file and start making changes.

Hmm, maybe this will work...:
1. set `bufhidden=wipe` on those buffers
2. on BufEnter event, unset that 

I'll try that when I get a chance 😄

**Comment by mehalter** [comment]
This is mainly what the `transient` option  that was added in this PR helps with: https://github.com/MagicDuck/grug-far.nvim/pull/139

if you set `transient = true` then the buffers will have `bufhidden=wipe` set. I'm not sure if this is enough for your use case @kah-ell

**Comment by MagicDuck** [comment]
@mehalter as far as I understand, the buffers referenced are not the `grug-far` buffer, but the ones that are opened when you press the `<down>` and `<up>` arrows in normal mode in `grug-far` to navigate/preview results.

**Comment by mehalter** [comment]
ohhhh I see, I'm so sorry for the noise....

**Comment by MagicDuck** [comment]
no problem, I see you trying to help as a positive 😄

**Comment by MagicDuck** [comment]
should be fixed now! Only buffers that you consciously visit will remain in the buffers list. Feel free to reopen if you still see the issue!

**Comment by kah-ell** [comment]
Oh wow! Thank you so much!

It works flawlessly for me. No more buffers flooding the buflist and when I jump to a file from the grugfar result list, it conveniently survives the closing of grugfar.

Besides that, just found out that you can modify the lines in the result on the fly. What a nice and handy feature.

Thanks again, mate. Grug-Ell happy *ugh*. :)

@mehalter: Thx for helping man, pretty happy with that kind of noise. :)

**Comment by MagicDuck** [comment]
haha, great to hear! Live long and prosper, grug brother! :P
