### ISSUE TITLE
Allow ignoring some matches and per-match replacement

### ISSUE THREAD

**Issue by serhez** [MagicDuck/grug-far.nvim#27]
A key feature of `spectre` is to perform a replacement match-per-match (one by one) and to remove some matches from the list to then replace all remaining matches that have not been removed. Is this possible with this plugin? Thank you! :)

**Comment by MagicDuck** [comment]
This is not possible atm, but looks like what would be available if https://github.com/MagicDuck/grug-far.nvim/issues/24 gets implemented. 

There is a sort of workaround in that you could run nvim builtin search replace on the results buffer with confirm on each replace and then do a Sync Edits, but that is not super convient

**Comment by serhez** [comment]
Thanks for the reply! Looking forward to #24 then. I will add a few suggestions in that issue as well 👍🏻
