### ISSUE TITLE
[Bug] Toggle flag binding toggles on the wrong line with multiline search

### ISSUE THREAD

**Issue by Ajaymamtora** [MagicDuck/grug-far.nvim#273]
<img width="949" alt="Screenshot 2024-09-25 at 22 10 26" src="https://github.com/user-attachments/assets/6b1508d4-47c3-4519-a9e0-98d79d7b9009">

Seems to be toggling the flag on the wrong line when theres a multiline search or multiline replace, it should account for the varying number of lines of input in these fields.

Im using the config from the readme

```lua
    local grp = vim.api.nvim_create_augroup("my-grug-far-custom-keybinds", { clear = true })
    vim.api.nvim_create_autocmd("FileType", {
      group = grp,
      pattern = { "grug-far" },
      callback = function()
        vim.keymap.set("n", "<M-l>", function()
          local state = unpack(require("grug-far").toggle_flags({ "--fixed-strings" }))
          vim.notify("grug-far: toggled fixed strings " .. (state and "ON" or "OFF"))
        end, { buffer = true })
      end,
    })
```

**Comment by MagicDuck** [comment]
good catch, I forgot to fix this one when I added multiline input support. Should be good now! 😄
