### ISSUE TITLE
How to search/replace the entire line?

### ISSUE THREAD

**Issue by fredrikaverpil** [MagicDuck/grug-far.nvim#274]
Hi 👋  and thank you for this absolutely essential Neovim plugin!

I've been struggling to figure out how I can search for a string which represents a whole line in my codebase, which I want to completely remove from all files where it's been found. I'm using this search regex: `\S*tt := tt` as I have different number of tabs in front of `tt := tt`.

But no matter what flag or variation I try, I end up having this line being replaced with an empty line. I actually want the line removed completely, like so:

```diff
func Something() {
	tc := getCases()
	for _, tt := range tc {
-		tt := tt
		...
	}
}
```

But this is what I keep getting:

```diff
func Something() {
	tc := getCases()
	for _, tt := range tc {
-		tt := tt
+
		...
	}
}
```

Has this already been answered somewhere, or what should I do to actually pull this off?

**Comment by MagicDuck** [comment]
hi @fredrikaverpil , you'll have to update since I pushed a fix for a small bug in this area, but essentially the following worked for me (you have to do a multiline search and include the `\n`):
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/08af5c72-8072-4049-8837-d4ee8354aa7d">

**Comment by MagicDuck** [comment]
one min, broke a test, haha

**Comment by MagicDuck** [comment]
hmm, it's taking a bit longer than I thought, I'll need to take off but will take a look later

**Comment by MagicDuck** [comment]
kk, fixed now! Feel free to reopen if you see any issues 😄

**Comment by fredrikaverpil** [comment]
@MagicDuck awesome, works beautifully! ❤️
Huge thanks for this!

**Comment by fredrikaverpil** [comment]
Btw, I'd like to make a donation to grug-far and yourself in case you open up for [GitHub sponsors](https://github.com/sponsors) (or similar).

**Comment by MagicDuck** [comment]
Thank you! I don’t plan to do that for the foreseeable future as it’s purely a passion project and my day job provides enough, but I do appreciate the sentiment! :)
