### ISSUE TITLE
[Bug] Delete matches (replace with empty string) doesnt work

### ISSUE THREAD

**Issue by Ajaymamtora** [MagicDuck/grug-far.nvim#276]
I get "no changes to sync!"

With the following setup:

![image](https://github.com/user-attachments/assets/1599539a-f980-48e0-ae39-69db5cea14b5)

**Comment by MagicDuck** [comment]
you need to add `--replace=` to `Flags` as documented here: https://github.com/MagicDuck/grug-far.nvim?tab=readme-ov-file#syncing-results-lines-back-to-originating-files

since we can't differentiate between a pure search and replace with empty string.
