### ISSUE TITLE
Split highlight affected after `<localleader>c`

### ISSUE THREAD

**Issue by savchenko** [MagicDuck/grug-far.nvim#284]
A strange bug indeed. Steps to reproduce:

1. Open file in nVim v0.10.1, `set ft=jinja`
3. Open Grug
4. Execute `<localleader>c`

Highlighting completely disappears from the file opened in the remaining split.

**Comment by MagicDuck** [comment]
interesting ... does this only happen from `jinja` filetype?

**Comment by MagicDuck** [comment]
Ah, that last error is a different thing. I know where it's coming from and will address.

**Comment by MagicDuck** [comment]
btw, I tried creating an html file and doing `:set ft=jinja` on it, and it loses highlighting immediately...
![Uploading image.png…]()

**Comment by MagicDuck** [comment]
closing this as there's been no reply for a week. Feel free to reopen.
