### ISSUE TITLE
There is no an option to hide the help line

### ISSUE THREAD

**Issue by fpohtmeh** [MagicDuck/grug-far.nvim#285]
Reasons to have it:
- It takes two lines if opened as `split`
- Help is useful for users who aren't familiar with the plugin. Experienced users don't need it
- Plugins like which-key eliminates the need for the  helpline

**Comment by MagicDuck** [comment]
makes sense to add an option. Note that it would only save one line though as the virtual line labels for the inputs require at least one blank line above them 😄 .

**Comment by MagicDuck** [comment]
@fpohtmeh added option 😄 
just use this config:
```lua
      {
        helpLine = {
          enabled = false,
        },
      }
```

<img width="1261" alt="image" src="https://github.com/user-attachments/assets/5e9889c3-cbbc-4ece-b5dc-f17fd5cc2d28">
