### ISSUE TITLE
Bug: Resulting multiline replacement string duplicated

### ISSUE THREAD

**Issue by mjrogozinski** [MagicDuck/grug-far.nvim#295]
Input file:
```
/some/path/config
/some/other/config

/some/path/config
/some/other/config
```

GrugFar commands:
```
Search:
/some/path/config
/some/other/config
Replace:
/some/path/config
/some/different/config
Files Filter: # default, not changed
Flags:
--fixed-strings --multiline # or -U
```

Action:
```
<leader>r
```

# Current result:
```
/some/path/config
/some/different/config

/some/path/config
/some/different/config

/some/path/config
/some/different/config
```

# Expected result:
```
/some/path/config
/some/different/config

/some/path/config
/some/different/config
```

## History entry:
```
Engine: ripgrep
Search: /some/path/config
| /some/other/config
Replace: /some/path/config
| /some/different/config
Files Filter: 
Flags: --fixed-strings --multiline
Paths: 

```

### Comment:
For some reason when replacing multiple lines, extra lines from "Replace:" appear at the end of the file.

**Comment by MagicDuck** [comment]
hi @mjrogozinski, thanks for reporting! Just tried it though and I cannot reproduce it :confused: 

I am no `ripgrep 14.1.0`. What version are you on?

**Comment by mjrogozinski** [comment]
I have checked it with 14.1.0 on a mac and indeed you are right. The problem does not occur.
As for the version used earlier, I will have to check during the weekend. It was on my home Linux PC.

Still, let's close this issue for now.

**Comment by mjrogozinski** [comment]
Indeed wrong ripgrep version was to blame. Updating 13.0.0 to the newest fixed the issue.

The plugin works like a charm. Thank you!
