### ISSUE TITLE
Using multiple engines?

### ISSUE THREAD

**Issue by sztomi** [MagicDuck/grug-far.nvim#297]
I learned about `astgrep` from the docs here. It seems super useful in some situations, but by default I would want to keep ripgrep. Is it possible to configure grug-far in a way that it is able to invoke both?

**Comment by MagicDuck** [comment]
Sure, I mean that’s how it is by default :). Just hit <localleader>e to switch engine when you need astgrep and hit that again to go back to ripgrep.
