### ISSUE TITLE
How use gurg.nvim in lazyvim

### ISSUE THREAD

**Issue by takayums** [MagicDuck/grug-far.nvim#301]
After searching and entering the word you want to change, how do you confirm it in lazyvim? I'm confused

**Comment by MagicDuck** [comment]
Hi @takayums , I would recommend reading the README.md of this project. But essentially it boils down to executing an action bound to a keybinding. For replace action, it is bound to loacalleader+r in normal mode by default. You can see all actions by hitting ‘g?’

**Comment by takayums** [comment]
thanks, sorry i didn't read your documentation
