### ISSUE TITLE
Persist options

### ISSUE THREAD

**Issue by mainendra** [MagicDuck/grug-far.nvim#303]
It would be really useful to persist options (filesFilter, flags and paths)
Use case
- Search xxx with flags like ignore test files in given folder (path)
- Search yyy keeping last used params (same flags and paths)

**Comment by MagicDuck** [comment]
The first use case is just launching grug-far with prefills. You can already do that.
Second use case sounds very similar to the already existing history feature.

**Comment by mainendra** [comment]
@MagicDuck - Use case is two persist all options when you search for any highlighted word or word under cursor. So, is there a way to get opened buffer option. something like `getInstanceConfig({instanceName})` so that I can open search for different word (under cursor or highlighted) using same config.

**Comment by MagicDuck** [comment]
> So, is there a way to get opened buffer option. something like getInstanceConfig({instanceName}) so that I can open search for different word (under cursor or highlighted) using same config.

We can definitely expose a `get_instance_inputs` if we think that would be useful. 

> Update: Thanks, I think what I want is when you close and open same instance then persist the last config. Basically same functionality as update_instance_prefills (clearOld=false)

If what you want is to re-use the last history entry (no matter which instance generated it), we could add an option like `history.autoLoadLastEntry`. When this option is true, it will prefill with the last entry in history and overwrite with prefills you give it on top. So for example you could use it like:
```lua
require('grug-far').open({ history = { autoLoadLastEntry = true }, prefills = { search = vim.fn.expand("<cword>") } })
``` 
If you want it to be instance specific, then we can provide `get_instance_inputs` and you can do something like:
```lua
      local last_inputs = {}
      vim.keymap.set({ 'n', 'x' }, '<leader>sw', function()
        local prefills = vim.deepcopy(last_inputs)
        prefills.search = vim.fn.expand('<cword>')

        grugFar.open({
          onUnload = function(instanceName)
            last_inputs = grugFar.get_instance_inputs(instanceName)
          end,
          prefills = prefills,
        })
      end, { desc = 'grug-far: search, using last options' })
```

> Update2: is it possible to pick history without clearing old?

no, that would be weird...

**Comment by mainendra** [comment]
@MagicDuck - Thank you. This is really helpful. I think we can keep this plugin simple. No need to make any change.

Actually I'm trying to achieve IDE (e.g. vscode) like functionality where you will have only one search window at a time. I'm able to achieve it using existing functions and options, basically use instanceName to keep it same single instance. I'm working on multiple project so sometime I need to filter test files or automation files, etc while searching in project and I'm using history to save different filters. Also I'm closing buffer instead of quitting it so that I can use `update_instance_prefills` function without clearing existing filters. Just need to create a small utility function.

Again, Thank you. I'm closing this ticket.

**Comment by MagicDuck** [comment]
All good then! :)
