### ISSUE TITLE
rg `--path-separator` option not working

### ISSUE THREAD

**Issue by doongjohn** [MagicDuck/grug-far.nvim#304]
my config:
```lua
require 'grug-far'.setup {
  engines = {
    ripgrep = {
      extraArgs =
          '--no-heading -.ni --path-separator=/'
          .. ' -g !.git'
          .. ' -g !.github'
          .. ' -g !*cache'
          .. ' -g !obj'
          .. ' -g !.objs'
          .. ' -g !.deps'
          .. ' -g !bin'
          .. ' -g !out'
          .. ' -g !build'
          .. ' -g !target'
          .. ' -g !vendor'
          .. ' -g !dist'
          .. ' -g !node_modules'
          .. ' -g !.svelte-kit'
          .. ' -g !zig-out'
          .. ' -g !.godot',
    },
  },
  windowCreationCommand = 'vert topleft split',
  wrap = false,
}
```
I'm on windows but I want to set path separator to `/` because of this issue: https://github.com/nvim-telescope/telescope.nvim/issues/2446

However, it still uses `\` even if I set `--path-separator` to `/`.

**Comment by MagicDuck** [comment]
hmm, I think it's ripgrep `--json` option itself that does not respect `--path-separator`.
<img width="2262" alt="image" src="https://github.com/user-attachments/assets/f65304b1-a768-4a8f-897e-ef6d0d06364c">

Are you seeing an actual bug when triggering the `Open` action? I do wrap it with `fnameescape()` here:
https://github.com/MagicDuck/grug-far.nvim/blob/190c03d54e8976491e6e49acb97087bf4182b079/lua/grug-far/actions/openLocation.lua#L80

**Comment by doongjohn** [comment]
If I open a file `src\routes\(csr)\+layout.ts` with the open action (`,o`) the file is empty.
![Recording 2024-11-13 at 10 43 50](https://github.com/user-attachments/assets/1b981a23-f7b1-4ea9-9bf4-91846c284973)

If I do `<c-g>` in that empty file, the path is incorrect: 
![image](https://github.com/user-attachments/assets/0c973256-98ac-4109-8efc-59f3bf66010d)

**Comment by MagicDuck** [comment]
hi @doongjohn, I have incorporated logic from `neo-tree.nvim` when escaping the file paths for opening.
They seem to have gone through a long history of fixes in this area and apparently replacing `\` with `/` is not always ideal since it can confuse other plugins that rely on the right separator for the platform. Although doing that is always an option if it ends up not working.

I can't easily test on windows myself. Can you grab the latest version and check that opening is working fine now?

**Comment by doongjohn** [comment]
It's working really well! Thank you for the quick fix!

**Comment by MagicDuck** [comment]
Great! Thanks for checking!
