### ISSUE TITLE
Ripgrep globbing on "any-depth" folder search - No such file or directory

### ISSUE THREAD

**Issue by alainrk** [MagicDuck/grug-far.nvim#306]
Hi, first of all amazing project!
I've been trying grug-far as Lazy included it recently, but I have some strange behaviour with globbing so I was trying to understand what I'm missing and playing around with the syntax.

Here a simple use case porting the correspondent rg command to grug but I get this error:

![CleanShot 2024-11-18 at 14 47 35@2x](https://github.com/user-attachments/assets/bd3e642b-0e38-4b30-b999-4ea2fb5917b6)

Here the original rg command:

![CleanShot 2024-11-18 at 14 45 36@2x](https://github.com/user-attachments/assets/71780f53-5e5a-499e-9198-fa354f0707ef)

I have also tried using the `-g` flag but I get the same.

Here the output of `--debug`:
```
rg: DEBUG|rg::flags::parse|crates/core/flags/parse.rs:97: no extra arguments found from configuration file
rg: DEBUG|rg::flags::hiargs|crates/core/flags/hiargs.rs:1260: found hostname for hyperlink configuration: adler.local
rg: DEBUG|rg::flags::hiargs|crates/core/flags/hiargs.rs:1270: hyperlink format: ""
rg: DEBUG|rg::flags::hiargs|crates/core/flags/hiargs.rs:174: using 12 thread(s)
rg: DEBUG|grep_regex::config|crates/regex/src/config.rs:175: assembling HIR from 1 fixed string literals
rg: DEBUG|globset|crates/globset/src/lib.rs:453: built glob set; 0 literals, 0 basenames, 12 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
rg: **/second: No such file or directory (os error 2)
```

**Comment by MagicDuck** [comment]
hi @alainrk , thanks for the kind words 😄 

Regarding the issue you are seeing, the rg command that `grug-far` issues will be done relative to your current working directory (`:=vim.fn.getcwd()` to see it, or maybe just `:pwd`), but it's spawned as a process directly, so shell expansion for paths is not supported. Using `**/something/*` as a Files Filter (`-g` flag) works though.
 
You can also trigger this action to see the command that is run:
```
   - Toggle Show Search Command <,p>     Toggle showing search command. Can be useful for debugging purposes.
```

<img width="824" alt="image" src="https://github.com/user-attachments/assets/8491cdbe-2cae-436f-9a22-b40ffb2c27e7">

**Comment by alainrk** [comment]
Ah, I see now. My bad then, thank you for the great explanation, it makes sense now! Thanks!
