### ISSUE TITLE
[Bug] Inconsistent regex replace doesn't replace properly with groups

### ISSUE THREAD

**Issue by Ajaymamtora** [MagicDuck/grug-far.nvim#310]
Not sure why, but in this scenario:

![image](https://github.com/user-attachments/assets/c1d0df2e-fd6f-4d4d-b17f-05b601466f5a)

You can clearly see that some of the matches dont replace with the back reference properly. e.g. 5:27:import ContactMe from '../components/ContactMe.astro'
5:27:import ContactMe from '../components/ContactMe.astro'

I've used the same input with rip-substitute and it works fine, so not sure whats going on here

**Comment by MagicDuck** [comment]
was an issue with dotall specifically. Should be fixed now!
Let me know if you still have problems!

**Comment by MagicDuck** [comment]
added another fix since the new `\0` match separator screwed up some cases
