### ISSUE TITLE
[Bug] Open action does not highlight the target line if the search file path is limited to only one file.

### ISSUE THREAD

**Issue by ravenxrz** [MagicDuck/grug-far.nvim#311]
<img width="1385" alt="image" src="https://github.com/user-attachments/assets/ecdf3615-bffc-42f9-af33-815046129003">

Expect:
<img width="1530" alt="image" src="https://github.com/user-attachments/assets/28734ce6-2dd5-428e-a048-23a8e787f1f5">

**Comment by MagicDuck** [comment]
hmm, I can't seem to reproduce it.
Do you have more exact steps?

Also you can try it with a minimal reproduction config, to eliminate the possibility of some other plugin or config causing this. ex:
`repro.lua`:
```lua
local root = vim.fn.fnamemodify('~/.nvim_repro', ':p')
-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end
-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

vim.g.maplocalleader = ','
-- install plugins
local plugins = {
  -- do not remove the colorscheme!
  'folke/tokyonight.nvim',
  {
    "MagicDuck/grug-far.nvim",
    config = function()
      require('grug-far').setup({})
    end,
  },
  -- add any other pugins here
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

-- add anything else here
-- vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
```
Then run with:
```sh
nvim -u repro.lua
```

**Comment by ravenxrz** [comment]
Ohhh. I know. The plugin does not provide a highlight target line feature. It's just because I configured the cursor line highlighting. When I jump to the target by pressing <enter>, the line is highlighted automatically.
So the question is converted to: can we highlight the target line when pressing <localleader>o (open action)?

**Comment by MagicDuck** [comment]
hmm, but that's how it works by default if you have:
```lua
vim.opt.cursorline = true
```
here's an example with the minimal reproduction and setting the cursorline to red (i also commented out the colorscheme line)
<img width="1882" alt="image" src="https://github.com/user-attachments/assets/2cf84218-71ce-4117-a355-81929a22f2d9">

**Comment by ravenxrz** [comment]
I record a  GIF to demonstrate if limit file path to only one file, the problem still remains:

![](https://ravenxrz-blog.oss-cn-chengdu.aliyuncs.com/img/oss_img20241203_142328.gif)

The GIF is too big; if it cannot be displayed on GitHub, please click https://ravenxrz-blog.oss-cn-chengdu.aliyuncs.com/img/oss_img20241203_142328.gif to download it.

Can you reproduce this problem on your side?

**Comment by MagicDuck** [comment]
>  Can you reproduce this problem on your side?
No, I cannot! What you were doing in the GIF is exactly the same as the screenshot I posted above yesterday.

Were you able to reproduce using the minimal `repro.lua` file?

**Comment by MagicDuck** [comment]
btw, what's your ripgrep version, mine is:
```
❯ rg --version                                                                                                                                                                                                                                                                                                      2s
ripgrep 14.1.0
```

**Comment by ravenxrz** [comment]
> btw, what's your ripgrep version, mine is:
> 
> ```
> ❯ rg --version                                                                                                                                                                                                                                                                                                      2s
> ripgrep 14.1.0
> ```

Thank you for your reply; my rg version is the same as yours. I used repro.lua, and the behavior is now as expected. It seems another plugin is causing this strange behavior. I disabled the blue-green bracket highlighting plugin you mentioned yesterday, but the problem persists. I'll probably have to disable plugins one by one to track down the culprit.

**Comment by ravenxrz** [comment]
> > Can you reproduce this problem on your side?
> 
> No, I cannot! What you were doing in the GIF is exactly the same as the screenshot I posted above yesterday.
> 
> Were you able to reproduce using the minimal `repro.lua` file?
> 
> Alternatively you can try to debug and see what happens at this line:
> 
> https://github.com/MagicDuck/grug-far.nvim/blob/55333ff5eef5f6d03828b4c52a25c7b505c4d19c/lua/grug-far/actions/openLocation.lua#L115
> 
> 
> print out `location.lnum` and see if it's correct...

btw, the `location.lnum` is correct even in my env.

**Comment by ravenxrz** [comment]
I found the culprit: nvim-focus/focus.nvim. I'll close this issue.

**Comment by MagicDuck** [comment]
thank you for circling back! 😄
