### ISSUE TITLE
Remove match when using <localleader>l (Sync Line) on an item

### ISSUE THREAD

**Issue by seanturner026** [MagicDuck/grug-far.nvim#313]
Thanks for this Plugin, slowly honing in on eliminating vscode completely :) (multi-line editing is the last holdout). 

Is it possible when using `<localleader>l` (`Sync Line`) to remove the line item that was just synced from the matches buffer? As in re-generate matches without the item I just synced? 

<img width="847" alt="Screenshot 2024-12-02 at 9 13 12 PM" src="https://github.com/user-attachments/assets/57b17efc-67e8-4326-8c28-8e26613b1d73">

Considering the above screenshot, calling `Sync Line` on the first item (where the cursor is) would remove the first item and move the cursor to (`filetypes`) item which would be the new first item.

My bad if this is already available. I had a look at the options and scanned all of the previous issues and didn't see anything.

**Comment by MagicDuck** [comment]
hmm, interesting, I haven't quite used it that way yet 😄 
what we've been doing so far is remove the changes you don't want made and the use `Sync All`
I'll have to think about this use case...

**Comment by MagicDuck** [comment]
hi @seanturner026 ,
I added two new actions to support incremental syncing of changes with removal from buffer. Let me know what you think.
```
   - Apply Next <,j>                     Apply change at current line, remove it from buffer and move cursor to next change
   - Apply Prev <,k>                     Apply change at current line, remove it from buffer and move cursor to prev change
```

**Comment by MagicDuck** [comment]
reminder for myself to add unit tests 😄

**Comment by seanturner026** [comment]
Works snappily and is exactly as expected! Thanks so much!

**Comment by MagicDuck** [comment]
Great to hear! :)

**Comment by seanturner026** [comment]
Feel free to close! I haven't as you mentioned adding unit tests

**Comment by MagicDuck** [comment]
unit tests added, closing!
