### ISSUE TITLE
Make mapping more visible

### ISSUE THREAD

**Issue by z0rzi** [MagicDuck/grug-far.nvim#317]
There is no mention of the key mappings in the readme, and the mappings in the search buffer look like this for me:

![image](https://github.com/user-attachments/assets/e0cbc526-cf7d-49c8-a8ee-d451b2607446)
(*I can only see 5 of them*)

And the mappings don't appear when I hit `g?`.

I had to go through the source code to find them, maybe I'm missing something?

**Comment by MagicDuck** [comment]
This is what you should see when you hit `g?`
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/3152b285-4805-475c-93cb-554df75a58f3">
I am guessing you have some config or plugin that messes with the mapping.
If you enter `nmap g?` while in the grug-far buffer, you should see:
<img width="685" alt="image" src="https://github.com/user-attachments/assets/b914b392-86b3-4f41-82d1-9e62008b6ced">

Also you can try it with a minimal reproduction config, to eliminate the possibility of some other plugin or config causing this. ex:
`repro.lua`:
```lua
local root = vim.fn.fnamemodify('~/.nvim_repro', ':p')
-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end
-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

vim.g.maplocalleader = ','
-- install plugins
local plugins = {
  -- do not remove the colorscheme!
  'folke/tokyonight.nvim',
  {
    "MagicDuck/grug-far.nvim",
    config = function()
      require('grug-far').setup({})
    end,
  },
  -- add any other pugins here
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

-- add anything else here
-- vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
```
Then run with:
```sh
nvim -u repro.lua
```

**Comment by MagicDuck** [comment]
note: you should also see a version of the mappings if you have which-key installed and hit `<localleader>`

**Comment by z0rzi** [comment]
Thanks for the answer, It looks like my colorscheme (or my terminal) isn't set up properly, the mappings don't appear on `g?`:
![image](https://github.com/user-attachments/assets/dbf82b7c-b9e3-4867-9514-772eda9275bd)

But they are there if I select the text:
![image](https://github.com/user-attachments/assets/92a9939e-f653-4ad0-b85e-f3c176257a00)

I'm using the defaults of gruvbox, it's surprising that they don't show up...

**Comment by MagicDuck** [comment]
hmm, the highlight for that is:
```
  GrugFarHelpWinActionKey = { default = true, link = 'Conceal' },
```
Maybe I can change it something else by default 🤔

**Comment by MagicDuck** [comment]
highlight for the key mapping is now linked to `Identifier` hl group. Hopefully that makes it more visible! Thank you for finding this issue 😄
