### ISSUE TITLE
[QUESTION] Right now, running GrugFar opens it in a split pane, is it possible to open it in a seperate buffer?

### ISSUE THREAD

**Issue by itse4elhaam** [MagicDuck/grug-far.nvim#318]
BTW, loving this plugin, Really appreciated.

**Comment by itse4elhaam** [comment]
Also, how do I add something like c to the replacement?

As in I want it to confirm before replacing each entry?

Thanks!

**Comment by MagicDuck** [comment]
hi, not sure what you mean about a separate buffer, as it already is a separate buffer...
Do you mean separate tab? If yes, you can use this option:
https://github.com/MagicDuck/grug-far.nvim/blob/55333ff5eef5f6d03828b4c52a25c7b505c4d19c/lua/grug-far/opts.lua#L118
```
windowCreationCommand = 'tab split'
```

> Also, how do I add something like c to the replacement?
> As in I want it to confirm before replacing each entry?

There is no such thing, but you can navigate through the results with  `<down>/<up>` arrows, delete lines for matches you don't changed and hit `<localleader>s` (Sync All).

**Comment by MagicDuck** [comment]
hi @itse4elhaam ,
I added two new actions to support incremental syncing of changes with removal from buffer. That will help with the confirm thing you were asking for.
```
   - Apply Next <,j>                     Apply change at current line, remove it from buffer and move cursor to next change
   - Apply Prev <,k>                     Apply change at current line, remove it from buffer and move cursor to prev change
```

**Comment by itse4elhaam** [comment]
> hi @itse4elhaam , I added two new actions to support incremental syncing of changes with removal from buffer. That will help with the confirm thing you were asking for.
> 
> ```
>    - Apply Next <,j>                     Apply change at current line, remove it from buffer and move cursor to next change
>    - Apply Prev <,k>                     Apply change at current line, remove it from buffer and move cursor to prev change
> ```

Thanks! Looking forward to using it!

**Comment by itse4elhaam** [comment]
Hey @MagicDuck , Another question:

Is there a way to search the current word under my cursor in GrugFar with a command?

Like can I pass it params to take in as the default string to search for?

**Comment by MagicDuck** [comment]
got it, seems like you mean tab. Just FYI, in vim terminology, you have the following relationship:
tabs (sometimes also called tabpages) contain windows (sometimes also called splits) which contain buffers.

So what you want to do is:
```lua
      require('grug-far').setup({
        windowCreationCommand = 'tab split',
      })
```
or if you want a one-off call:
```lua
:lua require('grug-far').open({ windowCreationCommand = 'tab split' })
```
