### ISSUE TITLE
setupGlobalOptOverrides not working in all cases

### ISSUE THREAD

**Issue by Sofistico** [MagicDuck/grug-far.nvim#328]
The function setupGlobalOptOverrides isn't recovering the original backspace on all cases, so far i have identified these situations that it doesn't return the original backspace:

- When  i try to hit `<C-c>` to exit insert mode.
- In this config the `q` doesn't works:
```lua
vim.api.nvim_create_autocmd('filetype', {
  group = augroup 'close_with_q',
  pattern = {
    'grug-far',
  },
  callback = function(event)
    vim.bo[event.buf].buflisted = false
    vim.keymap.set('n', 'q', '<cmd>close<cr>', {
      buffer = event.buf,
      silent = true,
      desc = 'quit buffer',
    })
  end,
})
```
- Closing the window on `<C-w> q` doesn't works.
- Closing on `!bd` also doesn't works.

The only key that worked was exiting insert mode with `<ESC>` and `<C-o>` .

This was the change i made to keep track of it:

```lua
local function setupGlobalOptOverrides(buf, context)
  local originalBackspaceOpt = vim.deepcopy(vim.opt.backspace:get())
  local function onInsertEnter()
    -- this prevents backspacing over eol when clearing an input line
    -- for a better user experience
    vim.opt.backspace:remove('eol')
    vim.notify("original" .. vim.inspect(originalBackspaceOpt))
  end
  local function onInsertLeave()
    vim.notify("before" .. vim.inspect(originalBackspaceOpt))
    vim.opt.backspace = originalBackspaceOpt
    vim.notify("after" .. vim.inspect(vim.opt.backspace:get()))
  end
```

**Comment by Sofistico** [comment]
I know this isn't wrong, since InsertLeave in the docs says that it doesn't work on `<C-c>` but I don't think this is intented behavior, since then if the user doesn't know what key to press to exit insert mode and/or closes the buffer/window, the original backspace won't be recovered.

**Comment by MagicDuck** [comment]
hi @Sofistico, good catch! Hmm, `backspace` option being global is such a pain!
Maybe we need to do things on `BufLeave` instead. I'll take a look

**Comment by MagicDuck** [comment]
@Sofistico can you check on latest? I think it should be fixed now 🤞

**Comment by Sofistico** [comment]
Yep, it's fixed.
Thx for fixing it so fast!

**Comment by MagicDuck** [comment]
No problem! Thanks for confirming! 👍
