### ISSUE TITLE
Freezing while viewing large matches vs Spectre

### ISSUE THREAD

**Issue by asilvadesigns** [MagicDuck/grug-far.nvim#338]
I've been having quite a hard time finding what the source is for the slowdown so I figured I'd just make an issue. 

I've noticed that when I search, regardless of what the search is, and even when I limit the search results Neovim locks up. I don't encounter this when using Spectre, I've tried disabling treesitter, ufo, modes, satellite, incline, any plugin that modifies the UI in some way and I can't restore the performance. Checkhealth shows nothing. I've tried within and without tmux, ghostty, alacritty, terminal, no difference.

The issue seems to be around wrapped lines, especially when those strings are huge.

Here's a video to show what I mean, I'll first open Grug and search for "require\(.*\)" then I'll do the same with Spectre using only ctrl-d to move down a page.

Nothing is shown in checkhealth, and my grug-far config is default, any help appreciated, thank you!

[![asciicast](https://asciinema.org/a/ZyVy7sjkWa3JWOjYCNJyYhH1p.svg)](https://asciinema.org/a/ZyVy7sjkWa3JWOjYCNJyYhH1p)

**Comment by MagicDuck** [comment]
How does nvim behave when you open the file with those long wrapped lines?
Have you tried with resultsHighlight and inputsHighlight opts disabled?
https://github.com/MagicDuck/grug-far.nvim/blob/c88435b825a35bfa468b47159709b3221976ecd1/lua/grug-far/opts.lua#L191

If those are what’s causing the issue, it’s probably worth disabling the treesitter highlight on long lines as  part of the default plugin logic.

**Comment by asilvadesigns** [comment]
It certainly helps, but it still chugs. The same issue occurs when opening the file in neovim regardless of grug, I'll close issue and look into disabling certain options for large files, thanks for helping debug!

**Comment by asilvadesigns** [comment]
It certainly helps, but it still chugs. The same issue occurs when opening the file in Neovim regardless of grug, I'll close issue and look into disabling certain options for large files, thanks for helping debug!

**Comment by MagicDuck** [comment]
@asilvadesigns just FYI that I was doing some perf improvements lately and I have fixed the situation where nvim would freeze due to very long lines. I worked around it by trimming those long lines to a configurable size (1000 chars by default). ex:

<img width="1251" alt="Image" src="https://github.com/user-attachments/assets/5ad08c16-9bd1-492a-b43e-0ba611c435b9" />

**Comment by asilvadesigns** [comment]
Nice!!
