### ISSUE TITLE
help: How to undo a Replace action

### ISSUE THREAD

**Issue by ficcdaf** [MagicDuck/grug-far.nvim#339]
Hi, the only reference to "undo" I could find in the readme was "recovery should be a simple undo away".
However, when I press `u` to undo, it only undoes the changes to the pattern I've made inside the `grug` buffer, and not the actual `<localleader>r` replace action I just did. Am I missing something obvious here?

**Comment by MagicDuck** [comment]
Hi @ficcdaf, undo at the level of replace is not supported. For that type of undo I recommend you rely on a versioning system like git. The quote you referenced was relying to the grug-far buffer itself.

**Comment by ficcdaf** [comment]
Ok that makes sense, thank you!
