### ISSUE TITLE
Add ability to repeat last search

### ISSUE THREAD

**Issue by mambusskruj** [MagicDuck/grug-far.nvim#47]
Spectre allows me to repeat last search. I find it useful sometimes, especially when there was some complex regex pattern.

I suggest keeping it simple and providing the ability to circle through search history with shortcuts. The trick is to keep in mind not only the search phrase but all the filters and options.

**Comment by MagicDuck** [comment]
hmm, good idea, I've also been thinking about a History function. Either with telescope or like you are saying just cycle through. One thing I am not clear on is when it should save the current "search" to history, would that be on buffer close?
As a user of this feature in spectre, let me know your thoughts on this. I haven't used that spectre functionality, just used that type of history thing back in intellij idea, haha.

**Comment by mambusskruj** [comment]
@MagicDuck Spectre's repeat feature is limited:
- Spectre saves only the last performed search
- The last performed search is the query executed before closing Spectre buffer.
- The option is available only within nvim session, so no persistent search history

Because of strict limitations and search only on leaving insert mode, it is easy to determine the feature's logic. 

> When it should save the current "search" to history
I think GrupFar should take similar logic on saving query as history item only after buffer close.

GrugFar could have a similar approach as Harpoon - make history persistent and separated by project.

**Comment by MagicDuck** [comment]
@mambusskruj ok, I've added history capabilities! See info here: https://github.com/MagicDuck/grug-far.nvim?tab=readme-ov-file#history

There's also config for it:
```lua
  -- search history settings
  history = {
    -- maximum number of lines in history file, end of file will be smartly truncated
    -- to remove oldest entries
    maxHistoryLines = 10000,

    -- directory where to store history file
    historyDir = vim.fn.stdpath('state') .. '/grug-far',

    -- configuration for when to auto-save history entries
    autoSave = {
      -- whether to auto-save at all, trumps all other settings below
      enabled = true,

      -- auto-save after a replace
      onReplace = true,

      -- auto-save after sync all
      onSyncAll = true,

      -- auto-save after buffer is deleted
      onBufDelete = true,
    },
  },
```

I had to do some major rework on the help header cause we were getting too many things in there and switched to using `<localleader>` for bindings as that is the vim recommended way. 

Decided not to do:
1. history entry dedupe - was too complex and seemed like it would be not worth + slow down as history file grows
2. per-project history - upon deeper thinking, I was not a able to decide on a good criteria to figure out "what is a project". Using CWD is not always right as the user might move around and do searches. Also, I would like to have my complex regexes accessible across projects. So decided against it 🤷 

Let me know what you think!

**Comment by MagicDuck** [comment]
ended up adding dedupe just for last entry
