### ISSUE TITLE
`Failed to rename buffer` error

### ISSUE THREAD

**Issue by adriafarres** [MagicDuck/grug-far.nvim#5]
Hello!

From reading the README, it seems the way you use GrugFar is to delete the buffer with `:bd`. For those of us who are used to simply closing buffers with `:q`, calling `:GrugFar` a second time displays the error

```
Error executing vim.schedule lua callback: ...al/share/nvim/lazy/grug-far.nvim/lua/grug-far/render.lua:47: Failed to rename buffer
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        ...al/share/nvim/lazy/grug-far.nvim/lua/grug-far/render.lua:47: in function 'render'
        ...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:57: in function <...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer.lua:56>

```

Would it be possible to handle this?

Thank you! :-)

**Comment by MagicDuck** [comment]
hmm, good catch! I'll investigate what's happening when I get a chance!

btw though, `:q` will not actually close the buffer, just remove the window in which the buffer exists. You can verify this by running `:buffers` after `:q`

**Comment by adriafarres** [comment]
When I said "close" I meant hide it, yeah :). Thanks for looking into it!

**Comment by acoffman** [comment]
I ran into the same issue.

Given this in the README:

>When you are done, it is recommended to close the buffer with the configured keybinding (see Configuration section above) or just :bd in order to save on resources as some search results can be quite beefy in size.

It seems that actually deleting the buffer is preferred. With the planned custom filetype in #7 would it perhaps make sense to set up a filetype specific autocmd for `BufHidden` events that just deletes the buffer?

**Comment by MagicDuck** [comment]
addressed both issues 😄 
> With the planned custom filetype in https://github.com/MagicDuck/grug-far.nvim/issues/7 would it perhaps make sense to set up a filetype specific autocmd for BufHidden events that just deletes the buffer?
Yeah, but that would be up the user, since some may prefer to have multiple buffers with different search results open for reference purposes for a while. I remember using this type of feature in Intellij Idea quite a bit, haha.

**Comment by adriafarres** [comment]
@MagicDuck Thank you :)
