### ISSUE TITLE
Cannot remove/disable keymaps

### ISSUE THREAD

**Issue by tsakirist** [MagicDuck/grug-far.nvim#63]
Hello thanks for the plugin!

I just noticed that we can no longer disable/remove some of the default keyamps with `''` or `false`.

The commit that probably broke this behavior: e324f781f757b3c6d44595d5a6133de52075413c

I would open a PR to fix it but currently there is no time, so I just opened an issue.

**Comment by MagicDuck** [comment]
Thanks for reporting, i will take a look soon!

**Comment by MagicDuck** [comment]
lemme know if you still see the problem and I'll reopen! 😄
