### ISSUE TITLE
Add keymap for popular options

### ISSUE THREAD

**Issue by t18n** [MagicDuck/grug-far.nvim#66]
I would like to request adding a keymap for popular options such as:
- Ignore case
- Hidden file

I think the option in `Flags` can have more priority.

**Comment by MagicDuck** [comment]
Hmm, I don't think this is a good idea as there are too many possible rg options and the help header is already quite crowded with actions.
If you want say "ignore case", it's really easy to just type `-i` in the `Flags` input. That's more in the spirit of grug-far where we edit the rg options as a buffer line.
The grug-far buffer has it's own filetype as well so it's easy to add an autocommand targeting that file type that adds keybindings which insert text in the Flags area.
Closing as not planned.

**Comment by epilande** [comment]
Is there a way to add custom actions? For example 
- `<localleader>i` to toggle ignore case 
- `<localleader>h` to toggle search hidden

**Comment by MagicDuck** [comment]
@epilande yep, that already exists. See the cookbook 🧑‍🍳 😄 
https://github.com/MagicDuck/grug-far.nvim?tab=readme-ov-file#create-a-buffer-local-keybinding-to-toggle---fixed-strings-flag

**Comment by epilande** [comment]
Nice that works! 

Another question, is there a way to toggle the Files Filter? For example, some searches I want to ignore test files. 
I tried using the `glob` pattern i.e. `--glob !{*.spec.*,mocks*}` but that didn't work.

**Comment by MagicDuck** [comment]
yeah, whatever you put in `Files Filter` gets passed to `--glob` and takes precedence.
