### ISSUE TITLE
Horizontal split feature

### ISSUE THREAD

**Issue by wustho** [MagicDuck/grug-far.nvim#76]
Can we have horizontal split please. Esp. botright direction. Personally I find it that lines being matched is too long for vertical split.

**Comment by MagicDuck** [comment]
hi @wustho, I added a new option to support this.
For what you were requesting you can set the following option:
```
  windowCreationCommand = 'botright split',
``` 
<img width="1097" alt="image" src="https://github.com/MagicDuck/grug-far.nvim/assets/95201/09d749fa-7037-465c-b581-23718ee0aea7">
