### ISSUE TITLE
[WINDOWS]: After replacing text the file gets put into READONLY

### ISSUE THREAD

**Issue by JustBarnt** [MagicDuck/grug-far.nvim#77]
After replacing text found from the search, on Windows (I tested on Linux to make sure this was a Windows only issue) it causes the file to get put in to a readonly state and you can no longer edit the file.

**Comment by MagicDuck** [comment]
hi @JustBarnt , problem is that I don't have windows, so I can only try to blindly chuck things at it...
Are you on nvim 0.10 as well on windows?

**Comment by JustBarnt** [comment]
I am on nightly, but I did also try nvim-0.10 and experienced the same. I think it has to do with `fs_open` using `CreateFileW` from the windows API instead of `open2`. But that's just from me trying to explore and see if I could spot a potential issue

**Comment by MagicDuck** [comment]
ah, so you are not talking about the grug-far buffer being not `modifiable`, but rather about the files that have replacements done themselves, correct?...

**Comment by MagicDuck** [comment]
btw, you might have already seen this, but this is how we overwrite the files:
```
https://github.com/MagicDuck/grug-far.nvim/blob/a00db650ed8d76286054e022b0ea12e84e132ede/lua/grug-far/utils.lua#L151
```
So maybe we could be passing some different flags on this line?
```
  uv.fs_open(path, 'w+', uv.constants.O_RDWR + uv.constants.O_TRUNC, function(err1, fd)
```

**Comment by MagicDuck** [comment]
seems related to this: https://github.com/libuv/libuv/discussions/4291

**Comment by MagicDuck** [comment]
alright, so I made a change to have it only use `O_TRUC` as that should be sufficient for overwrite according to the docs:
https://github.com/MagicDuck/grug-far.nvim/pull/79/files
that should hopefully make it go into the right case in libuv:
https://github.com/libuv/libuv/blob/be6b81a352d17513c95be153afcb3148f1a451cd/src/win/fs.c#L464

it's merged in https://github.com/MagicDuck/grug-far.nvim/pull/79
let me know if it addressed your issue...

**Comment by JustBarnt** [comment]
Wow that was so quick! I get into the office in about a couple hours so I will let you know for sure! Thank you so much! 

Also I totally forgot to mention even with this small issue on windows this find and replace plugin is incredible. Great work to you and all who've contributed!

**Comment by JustBarnt** [comment]
Sadly no that did not seem to resolve the issue. I still get the same error 
```
Could not write: lua\core\init.lua
EPERM: operation not permitted: lua\core\init.lua
```

**Comment by MagicDuck** [comment]
Thank you for your kind words 😄 

I think I might have figured it out with the help of a windows VM (was a total pain).
I ended up having to manually call fs_ftruncate to prevent windows from creating a new file.

Fix is in https://github.com/MagicDuck/grug-far.nvim/pull/81
Could you try again when you get a chance?

**Comment by JustBarnt** [comment]
You are amazing! Thank you! It works!!! It sucks that Windows is pain though with it's API. But thank you!

**Comment by MagicDuck** [comment]
Sweet, thanks for confirming! 👍 
I think the only other possible thing that could be screwed on windows is line endings on sync if you are dealing with a mix of `\r\n` and `\n`, but we'll deal with that as it comes, haha.
