### ISSUE TITLE
Asynchrony issues (?)

### ISSUE THREAD

**Issue by joaomendoncaa** [MagicDuck/grug-far.nvim#83]
# Problem

If I understand correctly and without looking at much code, the searching flow is asynchronous / "debounced from input". Because of that, we might have a couple of issues here. I mainly found 2 from the get go and I also have a question.

1. `Error executing vim.schedule lua callback: ...lazy/grug-far.nvim/lua/grug-far/render/resultsHeader.lua:80: Invalid 'end_row': out of range` when closing the grug buffer when there's still a search being executed (or some kind of update to the buffer)
2. When the above doesn't happen, a weird behaviour in the form of the results being partially written to the grug buffer and then not saved (obviously).
3. Can we get somehow rid **silently** and **forcefully** of all grug buffers when we close them? (I supose after the above is fixed, that should be possible or even implicit)

_Here's an unscripted demo of all the above_

https://github.com/MagicDuck/grug-far.nvim/assets/57664150/2215ffd5-448a-47cd-a0ce-275e3be064d0

Lastly, congratulations to all contributors and @MagicDuck. This extension is absolutely bonkers and I stumbled upon it by total accident which makes it even better. It completely kills zed's multibuffer tech, which is also amazing and the only thing I've been _upset_ over not having (a nice) access to in neovim.

Thank you. 🍻

**Comment by MagicDuck** [comment]
Thank you for those kind words @joaomendoncaa ! It's a great joy for me that people are loving grug-far 😄 

That's a good find! I think the fix probably boils down to forcefully aborting all async tasks when you close the buffer. I'll take a look and get back to you!

**Comment by joaomendoncaa** [comment]
What an absolute legend Magic! 🤟 Thank you.

Seems like the first 2 were fixed, now I just need to figure out this buffer list trouble. Maybe an autocommand that deletes the buffer when exiting a grug buffer.

**Comment by MagicDuck** [comment]
No problem!

So are you saying it still leaves an unnamed buffer around for you?

I am using Telescope buffers to list them, but maybe builtin buffers command shows something different?

**Comment by MagicDuck** [comment]
hmm, just tried with `:buffers` and don't see any leftover buffers...
Ah, I think I know what's going on after watching the video again. The leftover buffers are a side effect of running `tabnew`

**Comment by joaomendoncaa** [comment]
That completely fixed it, thank you.

**A naive shower thought suggestion**: You should explore more around this format of putting a bunch of buffers on the same buffer. You're building a great UX foundation here that could possibly be used in a bunch of other things besides search and replace. 

Probably a great idea to keep an eye out for [zed.dev](https://zed.dev) as this is one of the features that surely make it standout in terms of basic editor experience.

![image](https://github.com/MagicDuck/grug-far.nvim/assets/57664150/d5d7fb5c-586b-4077-9f4d-0cd8c0aa4a3b)

This is greatly improving neovim! Keep pushing! 🙌

**Comment by MagicDuck** [comment]
Great!
Thanks for the suggestion, it’s an interesting idea. I suppose it would be possible to make a multibuffer plugin/function that takes the same data as a quickfix list and shows a grugfar style results list. I am just having a hard time atm thinking of situations where that would be more useful than just a quickfix list, probably cause I never used zed, haha
