### ISSUE TITLE
Error attempting to call nvim__redraw when getting a lot of matches

### ISSUE THREAD

**Issue by enrique-villarrealp** [MagicDuck/grug-far.nvim#91]
Hi!

So far loving the plugin, great job! I have been seeing an error somewhat consistently when searching for a specific string, and obtaining a lot of matches:

```
   Error  00:23:18 msg_show.lua_error Error executing vim.schedule lua callback: ...m/lazy/grug-far.nvim/lua/grug-far/render/resultsList.lua:277: attempt to call field 'nvim__redraw' (a nil value)
stack traceback:
	...m/lazy/grug-far.nvim/lua/grug-far/render/resultsList.lua:277: in function 'callback'
	...cal/share/nvim/lazy/grug-far.nvim/lua/grug-far/utils.lua:55: in function 'throttledForceRedrawBuffer'
	.../nvim/lazy/grug-far.nvim/lua/grug-far/actions/search.lua:63: in function 'on_fetch_chunk'
	...nvim/lazy/grug-far.nvim/lua/grug-far/rg/fetchResults.lua:28: in function 'on_fetch_chunk'
	.../nvim/lazy/grug-far.nvim/lua/grug-far/rg/fetchWithRg.lua:100: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
<img width="1624" alt="image" src="https://github.com/MagicDuck/grug-far.nvim/assets/85933898/4812fb61-411b-45e8-8f63-6d9b9ff103b7">

Doesn't seem to cause any issues that I've seen other than an annoying-ish noice popup, but yeah. I'm on `nvim 0.9.5` with commit `cd4b7dd` of the plugin.

Let me know if I can provide more info to help fix this!

**Comment by MagicDuck** [comment]
Thank you for the kind words! 
Ah interesting, I knew that nvim__redraw was experimental, but did not realize it was new in nvim 0.10
I will add a check so it only gets called in 0.10, but if you want a more responsive snappy experience I suggest you upgrade as well ;)
