### ISSUE TITLE
Configurable leader key for keymaps

### ISSUE THREAD

**Issue by guruor** [MagicDuck/grug-far.nvim#96]
Most of the [default mappings](https://github.com/MagicDuck/grug-far.nvim/blob/main/lua/grug-far/opts.lua#L50-L62) are starting with `<localleader>`. People might have their custom bindings with `<localleader>`. In that case they will have to remap all the keymaps for the plugin like I did:

```
      local leaderKey = "<localleader>r"
      local opts = {
        keymaps = {
          replace = { n = leaderKey .. "r" },
          qflist = { n = leaderKey .. "q" },
          syncLocations = { n = leaderKey .. "s" },
          syncLine = { n = leaderKey .. "l" },
          close = { n = leaderKey .. "c" },
          historyOpen = { n = leaderKey .. "t" },
          historyAdd = { n = leaderKey .. "a" },
          refresh = { n = leaderKey .. "f" },
          abort = { n = leaderKey .. "b" },
          gotoLocation = { n = "<enter>" },
          pickHistoryEntry = { n = "<enter>" },
        },
      }
```

Here I am suggesting to have a configurable `leaderKey` which will allow users to reuse predefined sensible keymaps by just changing the leaderKey. 

Updated default config would look like this after suggested change:
```
{
   ...
   - Key prefix for default keymaps
   leaderKey = ",",

  -- shortcuts for the actions you see at the top of the buffer
  -- set to '' or false to unset. Mappings with no normal mode value will be removed from the help header
  -- you can specify either a string which is then used as the mapping for both normmal and insert mode
  -- or you can specify a table of the form { [mode] = <lhs> } (ex: { i = '<C-enter>', n = '<localleader>gr'})
  -- it is recommended to use <localleader> though as that is more vim-ish
  -- see https://learnvimscriptthehardway.stevelosh.com/chapters/11.html#local-leader
  keymaps = {
    replace = { n = leaderKey .. "r" },
    qflist = { n = leaderKey .. "q" },
     ...
    gotoLocation = { n = "<enter>" },
    pickHistoryEntry = { n = "<enter>" },
  },
  ...
}
```

**Comment by MagicDuck** [comment]
hi @guruor , thank you for the suggestion 😄 . Just trying to understand the use case more as at first glance it seems to be an edge case, or maybe something specific to your setup. 
As far as I understand, the purpose of `localleader` is to have buffer type specific bindings. Are you by chance using `localleader` when you should be using `leader` for your bindings instead?

**Comment by guruor** [comment]
Hi @MagicDuck , this might be specific user case but I have key mapping with `<localleader>r` to execute a operation on certain filetype. 

Following are the use cases with their filetype: 
- Make a http request with rest.nvim for `http` fieltype
- Execute visually selected query in `sql` filetype.
- Run preview of markdown file currently open

Here just to override this one mapping I had to override all the defaults of grug-far.nvim.

**Comment by MagicDuck** [comment]
@guruor so if you have it configured per-filetype why would it conflict? `grug-far` has it's own separate filetype.

I am assuming you could either use ftplugin or do something like the following to create filetype specific bindings...
```lua
vim.api.nvim_create_autocmd('FileType', {
  group = vim.api.nvim_create_augroup('my_http_binds' .. name, { clear = true })),
  pattern = { 'http' },
  callback = function()
    vim.keymap.set('n', '<localleader>r', function()
      -- do http request
    end, { buffer = true })
  end,
})
vim.api.nvim_create_autocmd('FileType', {
  group = vim.api.nvim_create_augroup('my_http_binds' .. name, { clear = true })),
  pattern = { 'sql' },
  callback = function()
    vim.keymap.set('n', '<localleader>r', function()
      -- run sql query
    end, { buffer = true })
  end,
})
...
```

**Comment by guruor** [comment]
@MagicDuck Ah, my bad. Didn't notice these bindings are local buffer bindings only and are limited to `grug-far` filetype. By quick look at default config I assumed that it might conflict with my bindings but thats not the case. Got to know about actual use of `<localleader>` mappings from your [referenced article](https://learnvimscriptthehardway.stevelosh.com/chapters/11.html#local-leader). 

Now that I understood the gap, this request makes no sense. You can close the issue.

**Comment by MagicDuck** [comment]
@guruor no worries 😄
