### ISSUE TITLE
Configure keybinding to toggle specific flag?

### ISSUE THREAD

**Issue by Ajaymamtora** [MagicDuck/grug-far.nvim#98]
Is there a way to configure a buffer local mapping to toggle "--fixed-strings" for example?

**Comment by MagicDuck** [comment]
I am not sure if this is worth the effort. Taking `--fixed-strings` as an example, if you look at the man page for `rg`, the shorthand for it is `-F`, so you can literally enable this by pressing `jjjA -F`, which is not too far from having a shortcut that you would also have to memorize...

Now if you really really want a keybind, you could do something like:
```lua
local function toggle_flag(flag)
  local flags = vim.fn.getline(6)
  local i, j = flags:find(' ' .. flag, 1, true)
  if i then
    flags = flags:sub(1, i - 1) .. flags:sub(j + 1, -1)
  else
    flags = flags .. ' ' .. flag
  end
  vim.fn.setline(6, flags)
end

vim.api.nvim_create_autocmd('FileType', {
  group = augroup('test'),
  pattern = { 'grug-far' },
  callback = function()
    vim.keymap.set('n', '<localleader>w', function()
      toggle_flag('--fixed-strings')
    end, { buffer = true })
  end,
})
```

Now the only part I could consider as having in the plugin API is `toggle_flag()`, so you would call it as `require('grug-far').toggle_flag(...)`

**Comment by MagicDuck** [comment]
@Ajaymamtora added `toggle_flags` (made it more generic so it can do multiple flags if needed 😄 )
see https://github.com/MagicDuck/grug-far.nvim?tab=readme-ov-file#create-a-buffer-local-keybinding-to-toggle---fixed-strings-flag

**Comment by MagicDuck** [comment]
@Ajaymamtora ah, that's a a good idea ... although we should be returning a list of T/F values since we take in a list of flags.  
I'll try to when I get some time, or you can make an PR if you prefer it quicker 😄

**Comment by MagicDuck** [comment]
@Ajaymamtora FYI, I've made the change and updated the example here:
https://github.com/MagicDuck/grug-far.nvim?tab=readme-ov-file#create-a-buffer-local-keybinding-to-toggle---fixed-strings-flag
